- type: entity
  abstract: true
  parent: [SolutionCryo, SolutionCompositeNormalStackable, BaseItem, BaseItemDestructible]
  id: MaterialBase
  description: A raw material.
  components:
  - type: Appearance
  - type: Sprite
    sprite: _Funkystation/Objects/Materials/materials.rsi # Funky
  - type: Item
    sprite: _Funkystation/Objects/Materials/materials.rsi # Funky
    size: Normal
  - type: Material
  - type: Tag
    tags:
    - RawMaterial
  - type: Extractable
    grindableSolutionName: composite

- type: entity
  abstract: true
  parent: MaterialBase
  id: BaseSheet
  components:
  - type: Tag
    tags:
    - Sheet
    - ConstructionMaterial
  - type: StaticPrice
    price: 0
