using Content.Client.UserInterface.Controls;
using Content.Shared._Impstation.Service;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Impstation.Service;

[GenerateTypedNameReferences]
public sealed partial class ServiceJobBoardMenu : FancyWindow
{
    //Funky begin - Fix deprecated function
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    //Funky end - Fix deprecated function

    public Action<string>? OnSelectButtonPressed;

    public ServiceJobBoardMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Update(ServiceJobBoardConsoleState state)
    {
        CurrentJobContainer.Children.Clear();

        // available jobs are generated by the station
        foreach (var job in state.AvailableJobs)
        {
            var entry = new ServiceJobEntry(_prototypeManager.Index(job), _entityManager);
            entry.OnSelectButtonPressed += () => OnSelectButtonPressed?.Invoke(job);

            entry.Disabled = state.ActiveJob != null;
            entry.Selected = state.ActiveJob == job;

            //Funky begin - Added a countdown to the job board UI
            if (entry.Selected && state.EndTime != null && state.CurTime != null)
                entry.Timer = (state.EndTime.Value - state.CurTime.Value).ToString(@"hh\:mm\:ss");
            //Funky end - Added a countdown to the job board UI

            CurrentJobContainer.AddChild(entry);
        }
    }
}
