using System.Linq;
using System.Numerics;
using System.Text;
using Content.Shared.Access;
using Content.Shared._Funkystation.Documents;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Content.Client.UserInterface.Controls;

namespace Content.Client._Funkystation.Documents.UI;

[GenerateTypedNameReferences]
public sealed partial class DocumentPrinterMenu : FancyWindow
{
    [Dependency] private IPrototypeManager _proto = null!;
    [Dependency] private IEntityManager _entMan = null!;

    private readonly SpriteSystem _spriteSystem;
    public event Action<string>? OnPrintRequested;
    public event Action? OnCopyRequested;
    public event Action? OnEjectRequested;

    private DocumentPrinterBoundUserInterfaceState? _lastState;
    private string? _currentCategory;
    private HashSet<string> _lastCategoryIds = new();

    public DocumentPrinterMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entMan.System<SpriteSystem>();

        SearchBar.OnTextChanged += _ => RefreshDocumentList();
        CopyButton.OnPressed += _ => OnCopyRequested?.Invoke();
        EjectButton.OnPressed += _ => OnEjectRequested?.Invoke();
    }

    public void UpdateState(DocumentPrinterBoundUserInterfaceState state)
    {
        _lastState = state;

        var newCategoryIds = state.DocumentsByCategory.Keys.ToHashSet();
        if (!newCategoryIds.SetEquals(_lastCategoryIds))
        {
            var previousSelection = _currentCategory;
            BuildTabs(state);
            _lastCategoryIds = newCategoryIds;

            // Keep the user on the same tab if it still exists, rather than
            // silently snapping them back to the first category.
            if (previousSelection != null && newCategoryIds.Contains(previousSelection))
                SelectCategory(previousSelection);
        }

        UpdateCopyPanel(state);
        RefreshDocumentList();
    }

    private void UpdateCopyPanel(DocumentPrinterBoundUserInterfaceState state)
    {
        var msg = new FormattedMessage();

        if (state.IsJammed)
        {
            msg.AddMarkupOrThrow($"[color=#d32f2f]{Loc.GetString("document-printer-jammed")}[/color]");
        }
        else if (state.IsPaperInserted)
        {
            var paperName = state.InsertedPaperName ?? Loc.GetString("document-printer-copy-unknown-paper");
            msg.AddMarkupOrThrow($"[color=#388e3c]{Loc.GetString("document-printer-copy-inserted", ("name", paperName))}[/color]");
        }
        else
        {
            msg.AddMarkupOrThrow($"[color=#808080]{Loc.GetString("document-printer-copy-empty")}[/color]");
        }

        CopySlotLabel.SetMessage(msg);
        EjectButton.Disabled = !state.IsPaperInserted;
        CopyButton.Disabled = !state.CanCopy;
    }

    private void BuildTabs(DocumentPrinterBoundUserInterfaceState state)
    {
        CategoryList.RemoveAllChildren();

        var categories = state.DocumentsByCategory.Keys
            .Select(id => _proto.TryIndex<DocumentCategoryPrototype>(id, out var cat) ? cat : null)
            .OfType<DocumentCategoryPrototype>()
            .OrderBy(cat => cat.Priority)
            .ToList();

        foreach (var cat in categories)
        {
            var button = new Button
            {
                ToggleMode = true,
                HorizontalExpand = true,
                Name = $"CategoryTab_{cat.ID}"
            };

            var content = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 8,
                Margin = new Thickness(4, 2),
                HorizontalExpand = true
            };

            content.AddChild(new TextureRect
            {
                Texture = _spriteSystem.Frame0(cat.Icon),
                TextureScale = new Vector2(1.5f, 1.5f),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                VerticalAlignment = VAlignment.Center
            });

            var displayName = Loc.GetString(cat.Name);

            var nameLabel = new Label
            {
                Text = displayName,
                VerticalAlignment = VAlignment.Center,
                HorizontalExpand = true
            };

            content.AddChild(nameLabel);

            if (cat.ScrambleName)
                StartScrambleAnimation(nameLabel, displayName);

            button.AddChild(content);

            var catId = cat.ID;
            button.OnPressed += _ => SelectCategory(catId);
            CategoryList.AddChild(button);
        }

        if (categories.Count > 0)
        {
            SelectCategory(categories[0].ID);
        }
    }

    private static readonly Random ScrambleRandom = new();
    private const string ScrambleChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%&*";

    /// <summary>
    /// Cosmetic letter scramble
    /// </summary>
    private void StartScrambleAnimation(Label label, string realText)
    {
        if (Disposed)
            return;

        var sb = new StringBuilder(realText.Length);
        foreach (var c in realText)
        {
            sb.Append(c == ' ' ? ' ' : ScrambleChars[ScrambleRandom.Next(ScrambleChars.Length)]);
        }

        label.Text = sb.ToString();

        Timer.Spawn(TimeSpan.FromMilliseconds(120), () => StartScrambleAnimation(label, realText));
    }

    private void SelectCategory(string categoryId)
    {
        _currentCategory = categoryId;

        foreach (var child in CategoryList.Children)
        {
            if (child is Button btn)
                btn.Pressed = btn.Name == $"CategoryTab_{categoryId}";
        }

        SearchBar.Text = string.Empty;
        RefreshDocumentList();
    }

    private void RefreshDocumentList()
    {
        DocumentList.RemoveAllChildren();

        if (_lastState is null)
            return;

        var query = SearchBar.Text.Trim();

        List<DocumentEntry> filtered;
        if (string.IsNullOrEmpty(query))
        {
            if (_currentCategory is null || !_lastState.DocumentsByCategory.TryGetValue(_currentCategory, out var docs))
                return;

            filtered = docs;
        }
        else
        {
            filtered = _lastState.DocumentsByCategory.Values
                .SelectMany(docs => docs)
                .Where(d => d.Name.Contains(query, StringComparison.OrdinalIgnoreCase))
                .ToList();
        }

        foreach (var doc in filtered)
        {
            DocumentList.AddChild(BuildDocumentRow(doc, _lastState.CanPrint));
        }

        if (filtered.Count == 0)
        {
            DocumentList.AddChild(new Label
            {
                Text = Loc.GetString("document-printer-no-results"),
                StyleClasses = { "LabelSubText" },
                Margin = new Thickness(4)
            });
        }
    }

    private Control BuildDocumentRow(DocumentEntry doc, bool canPrint)
    {
        var row = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 4)
        };

        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(8, 6)
        };

        var labelBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true
        };

        Color? nameColor = doc.Accessible ? null : Color.Gray;

        labelBox.AddChild(new Label
        {
            Text = doc.Name,
            ModulateSelfOverride = nameColor
        });

        if (!string.IsNullOrWhiteSpace(doc.Description))
        {
            labelBox.AddChild(new Label
            {
                Text = doc.Description,
                StyleClasses = { "LabelSubText" },
                ModulateSelfOverride = nameColor
            });
        }

        var printButton = new Button
        {
            Text = Loc.GetString("document-printer-print-button"),
            Disabled = !doc.Accessible || !canPrint,
            VerticalAlignment = VAlignment.Center
        };

        var docId = doc.Id;
        printButton.OnPressed += _ => OnPrintRequested?.Invoke(docId);

        if (!doc.Accessible)
        {
            var reqNames = doc.RequiredAccess
                .Select(tag => _proto.TryIndex<AccessLevelPrototype>(tag, out var lvl)
                    ? Loc.GetString(lvl.Name ?? tag)
                    : tag);

            row.ToolTip = Loc.GetString("document-printer-locked-tooltip", ("access", string.Join(", ", reqNames)));
            row.TooltipDelay = 0.2f;
        }

        box.AddChild(labelBox);
        box.AddChild(printButton);
        row.AddChild(box);

        return row;
    }
}
