using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI.POS;

[GenerateTypedNameReferences]
public sealed partial class PoSLockBox : Control
{
    public PoSLockBox()
    {
        RobustXamlLoader.Load(this);
    }

    // an unclaimed terminal needs a card in hand to claim it, so prompt for that instead of a PIN
    public void SetNeedsCard(bool needsCard)
    {
        PromptLabel.SetMessage(Loc.GetString(needsCard ? "pos-lock-present-card" : "pos-lock-prompt"));
    }
}
