using Content.Client.UserInterface.Controls;
using Content.Shared._Impstation.PersonalEconomy.Components;
using Content.Shared.Hands.Components;
using Content.Shared.Hands.EntitySystems;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Impstation.PersonalEconomy.UI.POS;

[GenerateTypedNameReferences]
public sealed partial class PoSMenu : FancyWindow
{
    [Dependency] private readonly IPlayerManager _playerMan = null!;
    [Dependency] private readonly IEntityManager _entityManager = null!;

    public Action<string>? OnNumberEntered;
    public Action? OnClearButtonPressed;

    public bool LockMode;

    private bool _accountOpen;
    private PoSLockBox? _lockBox;
    private bool _lockClaimed;

    public PoSMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CreateInvalidSetupBox();

        UIKeypad.OnEnterButtonPressed += s => OnNumberEntered?.Invoke(s);
        UIKeypad.OnClearButtonPressed += () => OnClearButtonPressed?.Invoke();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        CheckForCard();
        UpdateLockState();
    }

    private void UpdateLockState()
    {
        if (!LockMode || _lockBox is null)
            return;

        var hasCard = false;
        if (_playerMan.LocalEntity is { } realEnt && _entityManager.HasComponent<HandsComponent>(realEnt))
        {
            var handSystem = _entityManager.System<SharedHandsSystem>();
            foreach (var ent in handSystem.EnumerateHeld(realEnt))
            {
                if (!_entityManager.HasComponent<BankCardComponent>(ent))
                    continue;

                hasCard = true;
                break;
            }
        }

        var needsCard = !_lockClaimed && !hasCard;
        KeypadContainer.Visible = !needsCard;
        _lockBox.SetNeedsCard(needsCard);
    }

    private void CheckForCard()
    {
        if (LockMode || _accountOpen || _playerMan.LocalEntity is not { } realEnt || !_entityManager.HasComponent<HandsComponent>(realEnt))
        {
            return;
        }

        var handSystem = _entityManager.System<SharedHandsSystem>();
        foreach (var ent in handSystem.EnumerateHeld(realEnt))
        {
            if (!_entityManager.TryGetComponent<BankCardComponent>(ent, out var comp))
                continue;

            OnNumberEntered?.Invoke($"{comp.AccountNumber.Number:000000}");
            break;
        }
    }

    public void ClearKeypad()
    {
        UIKeypad.SetEnteredNumber("");
    }

    public void ClearBox()
    {
        MainContainer.RemoveAllChildren();
        _accountOpen = false;
        LockMode = false;
        _lockBox = null;
        ClearKeypad();
    }

    public PoSLockBox CreateLockBox(bool claimed)
    {
        ClearBox();
        var box = new PoSLockBox();
        MainContainer.AddChild(box);
        LockMode = true;
        _lockBox = box;
        _lockClaimed = claimed;
        UpdateLockState();
        return box;
    }

    public PoSSetupBox CreateSetupBox()
    {
        ClearBox();
        var box = new PoSSetupBox(true);
        MainContainer.AddChild(box);
        _accountOpen = true;
        KeypadContainer.Visible = false;
        return box;
    }

    public PoSSetupBox CreateInvalidSetupBox()
    {
        ClearBox();
        var box = new PoSSetupBox(false);
        MainContainer.AddChild(box);
        KeypadContainer.Visible = false;
        return box;
    }

    public PoSPaymentBox CreatePaymentBox()
    {
        ClearBox();
        var box = new PoSPaymentBox(true);
        MainContainer.AddChild(box);
        _accountOpen = true;
        //the review screen has nothing to type, so drop the keypad
        KeypadContainer.Visible = false;
        return box;
    }

    public PoSPaymentBox CreateInvalidPaymentBox()
    {
        ClearBox();
        var box = new PoSPaymentBox(false);
        MainContainer.AddChild(box);
        KeypadContainer.Visible = false;
        return box;
    }
}

