using Content.Shared._Impstation.PersonalEconomy.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI.POS;

[GenerateTypedNameReferences]
public sealed partial class PoSPaymentBox : Control
{

    public Action? TransactionConfirmed;
    public Action? TransactionCancelled;
    public Action? MerchantPressed;

    public PoSPaymentBox()
    {
        RobustXamlLoader.Load(this);
    }

    public PoSPaymentBox(bool valid)
    {
        RobustXamlLoader.Load(this);
        MainContainer.Visible = valid;
        NamingThingsIsHard.Visible = !valid;

        ConfirmTransactionButton.OnPressed += _ => TransactionConfirmed?.Invoke();
        CancelButton.OnPressed += _ => TransactionCancelled?.Invoke();
        MerchantButton.OnPressed += _ => MerchantPressed?.Invoke();
    }

    public void FillOutDetails(string name, AccountNumber number, int subtotal, int tax, float taxPercent, string reason)
    {
        NameAndNumberLabel.Text =
            Loc.GetString("pos-payment-name-and-number", ("name", name), ("number", $"{number.Number:000000}"));
        ChargeReasonLabel.Text =
            string.IsNullOrEmpty(reason) ? "" : Loc.GetString("pos-payment-reason", ("reason", reason));

        SubtotalLabel.Text = Loc.GetString("pos-payment-scrip-amount", ("amount", $"{subtotal:n0}"));
        TaxLabel.Text = Loc.GetString("pos-payment-tax-label", ("percent", $"{taxPercent:0.##}"));
        TaxAmountLabel.Text = Loc.GetString("pos-payment-scrip-amount", ("amount", $"{tax:n0}"));
        TotalLabel.Text = Loc.GetString("pos-payment-scrip-amount", ("amount", $"{subtotal + tax:n0}"));
    }
}

