using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI.POS;

[GenerateTypedNameReferences]
public sealed partial class TipMenu : FancyWindow
{
    // called with the chosen tip amount (0 = no tip)
    public Action<int>? OnTipChosen;

    private int _subtotal;

    public TipMenu()
    {
        RobustXamlLoader.Load(this);

        Tip15Button.OnPressed += _ => ChooseTip(15);
        Tip18Button.OnPressed += _ => ChooseTip(18);
        Tip20Button.OnPressed += _ => ChooseTip(20);
        Tip25Button.OnPressed += _ => ChooseTip(25);

        CustomButton.OnPressed += _ => CustomRow.Visible = !CustomRow.Visible;
        CustomConfirmButton.OnPressed += _ =>
        {
            if (int.TryParse(CustomBox.Text, out var amount) && amount >= 0)
                Finish(amount);
        };
        NoTipButton.OnPressed += _ => Finish(0);
    }

    public void SetSubtotal(int subtotal)
    {
        _subtotal = subtotal;
        CustomRow.Visible = false;
        CustomBox.Text = "";
        TipPreviewLabel.Text = Loc.GetString("pos-tip-preview", ("amount", $"{subtotal:n0}"));
    }

    // tip is a percentage of the pretax subtotal
    private void ChooseTip(int percent)
    {
        Finish(_subtotal * percent / 100);
    }

    private void Finish(int amount)
    {
        OnTipChosen?.Invoke(amount);
        Close();
    }
}
