using Content.Client.Message;
using Content.Client.RichText;
using Content.Client.UserInterface.Controls;
using Content.Shared.MassMedia.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Funkystation.HandheldNewsReader;

[GenerateTypedNameReferences]
public sealed partial class HandheldNewsReaderWindow : FancyWindow
{
    public event Action? OnNextButtonPressed;
    public event Action? OnPrevButtonPressed;

    public HandheldNewsReaderWindow()
    {
        RobustXamlLoader.Load(this);

        Next.OnPressed += _ => OnNextButtonPressed?.Invoke();
        Prev.OnPressed += _ => OnPrevButtonPressed?.Invoke();
    }

    public void UpdateState(NewsArticle article, int targetNum, int totalNum)
    {
        PageNum.Visible = true;
        ShareTime.Visible = true;
        Author.Visible = true;

        PageName.Text = article.Title;
        PageText.SetMessage(FormattedMessage.FromMarkupPermissive(article.Content), UserFormattableTags.BaseAllowedTags);

        PageNum.Text = $"{targetNum}/{totalNum}";

        var shareTime = article.ShareTimeString;
        ShareTime.SetMarkup(Loc.GetString("news-read-ui-time-prefix-text") + " " + shareTime);

        var author = Loc.GetString("news-read-ui-author-prefix") + " " + (article.Author ?? Loc.GetString("news-read-ui-no-author"));
        Author.SetMessage(FormattedMessage.FromMarkupPermissive(author), UserFormattableTags.BaseAllowedTags);

        Prev.Disabled = targetNum <= 1;
        Next.Disabled = targetNum >= totalNum;
    }

    public void UpdateEmptyState()
    {
        PageNum.Visible = false;
        ShareTime.Visible = false;
        Author.Visible = false;

        PageName.Text = Loc.GetString("news-read-ui-not-found-text");
        PageText.SetMessage(FormattedMessage.Empty);

        Prev.Disabled = true;
        Next.Disabled = true;
    }
}
