using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.CartridgeLoader;

[GenerateTypedNameReferences]
public sealed partial class SingleCartridgeLoaderWindow : FancyWindow
{
    public SingleCartridgeLoaderWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
