# Base mob components that originate from ES.
- type: entity
  id: ESBaseMob
  abstract: true
  components:
  - type: ESViewcone
  - type: ESViewconeOccludable
  - type: ESHoldToFace
  - type: ESPainFlash
  - type: GhostOnMove # todo this kinda doesnt make any sense and it should really just always happen if someone controls something and dies.
    # also the name doesnt maek any sense
