using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.Administration.UI.Logs;

[GenerateTypedNameReferences]
public sealed partial class PlayerMonitoringLogsWindow : DefaultWindow
{
    public PlayerMonitoringLogsWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
