using System.Linq;
using Content.Shared._Funkystation.Pager;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.Pager;

[GenerateTypedNameReferences]
public sealed partial class PagerCartridgeUiFragment : BoxContainer
{
    public event Action<int, string?>? OnSend;
    public event Action<int, string?>? OnMassPage;
    public event Action? OnCycleMode;

    public PagerCartridgeUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        var styleBox = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#111115"),
            BorderColor = Color.FromHex("#222228"),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 4,
            ContentMarginRightOverride = 4,
            ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 4,
        };

        NumberEdit.StyleBoxOverride = styleBox;
        CodeEdit.StyleBoxOverride = styleBox;

        NumberEdit.IsValid = text => text.Length == 0 || (text.Length <= 4 && text.All(char.IsDigit));
        CodeEdit.IsValid = text => text.Length == 0 || (text.Length <= 8 && text.All(char.IsLetterOrDigit));

        SendButton.OnPressed += _ => TrySend();
        ModeButton.OnPressed += _ => OnCycleMode?.Invoke();
    }

    public void UpdateState(PagerCartridgeUiState state)
    {
        OwnNumberLabel.Text = Loc.GetString("pager-window-own-number", ("number", SharedPagerSystem.FormatNumber(state.OwnNumber)));
        ModeButton.Text = Loc.GetString("pager-cartridge-mode", ("mode", Loc.GetString(SharedPagerSystem.ModeLocKey(state.Mode))));

        if (state.CurrentPage == null)
        {
            ScreenLabel.Text = Loc.GetString("pager-window-no-pages");
        }
        else
        {
            var entry = state.CurrentPage;
            ScreenLabel.Text = !string.IsNullOrWhiteSpace(entry.Code)
                ? Loc.GetString("pager-window-log-line-coded", ("sender", SharedPagerSystem.FormatNumber(entry.SenderNumber)), ("code", entry.Code))
                : Loc.GetString("pager-window-log-line", ("sender", SharedPagerSystem.FormatNumber(entry.SenderNumber)));
        }

        UpdateDirectories(state.Directories);
    }

    private void UpdateDirectories(List<PagerDirectory> directories)
    {
        DirectoryContainer.RemoveAllChildren();

        foreach (var directory in directories)
        {
            var prefix = directory.Prefix;

            var header = new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true, Margin = new Thickness(0, 6, 0, 0) };
            header.AddChild(new Label
            {
                Text = Loc.GetString("pager-cartridge-directory-title",
                    ("department", Loc.GetString(directory.DepartmentName)),
                    ("prefix", prefix.ToString("D2"))),
                StyleClasses = { "LabelHeading" },
                HorizontalExpand = true,
                ClipText = true,
            });

            var pageAll = new Button { Text = Loc.GetString("pager-cartridge-page-all") };
            pageAll.OnPressed += _ => OnMassPage?.Invoke(prefix, GetCode());
            header.AddChild(pageAll);

            DirectoryContainer.AddChild(header);
            DirectoryContainer.AddChild(new PanelContainer { StyleClasses = { "LowDivider" } });

            if (directory.Entries.Count == 0)
            {
                DirectoryContainer.AddChild(new Label
                {
                    Text = Loc.GetString("pager-cartridge-directory-empty"),
                    StyleClasses = { "LabelSubText" },
                });
                continue;
            }

            foreach (var entry in directory.Entries)
            {
                var number = entry.Number;

                var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true, SeparationOverride = 6 };
                row.AddChild(new Label { Text = entry.Name, HorizontalExpand = true, ClipText = true });
                row.AddChild(new Label { Text = entry.JobTitle, StyleClasses = { "LabelSubText" }, ClipText = true });

                var numberButton = new Button { Text = SharedPagerSystem.FormatNumber(number), MinWidth = 52 };
                numberButton.OnPressed += _ => NumberEdit.Text = SharedPagerSystem.FormatNumber(number);
                row.AddChild(numberButton);

                DirectoryContainer.AddChild(row);
            }
        }
    }

    private string? GetCode()
    {
        var rawCode = CodeEdit.Text.Trim();
        if (string.IsNullOrEmpty(rawCode) || !SharedPagerSystem.IsValidCode(rawCode))
            return null;

        return rawCode.ToUpperInvariant();
    }

    private void TrySend()
    {
        if (!int.TryParse(NumberEdit.Text, out var number) || !SharedPagerSystem.IsValidNumber(number))
            return;

        var rawCode = CodeEdit.Text.Trim();
        if (!string.IsNullOrEmpty(rawCode) && !SharedPagerSystem.IsValidCode(rawCode))
            return;

        OnSend?.Invoke(number, GetCode());
    }
}
