using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Funkystation.Pager;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.Pager;

[GenerateTypedNameReferences]
public sealed partial class PagerWindow : FancyWindow
{
    public event Action<int, string?>? OnSend;

    public PagerWindow()
    {
        RobustXamlLoader.Load(this);

        var styleBox = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#111115"),
            BorderColor = Color.FromHex("#222228"),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 4,
            ContentMarginRightOverride = 4,
            ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 4,
        };

        NumberEdit.StyleBoxOverride = styleBox;
        CodeEdit.StyleBoxOverride = styleBox;

        NumberEdit.IsValid = text => text.Length == 0 || (text.Length <= 4 && text.All(char.IsDigit));
        CodeEdit.IsValid = text => text.Length == 0 || (text.Length <= 8 && text.All(char.IsLetterOrDigit));

        SendButton.OnPressed += _ => TrySend();
    }

    public void UpdateState(PagerBoundUserInterfaceState state)
    {
        OwnNumberLabel.Text = Loc.GetString("pager-window-own-number", ("number", state.OwnNumber));

        if (state.CurrentPage == null)
        {
            ScreenLabel.Text = Loc.GetString("pager-window-no-pages");
            return;
        }

        var entry = state.CurrentPage;
        ScreenLabel.Text = !string.IsNullOrWhiteSpace(entry.Code)
            ? Loc.GetString("pager-window-log-line-coded", ("sender", entry.SenderNumber), ("code", entry.Code))
            : Loc.GetString("pager-window-log-line", ("sender", entry.SenderNumber));
    }

    private void TrySend()
    {
        if (!int.TryParse(NumberEdit.Text, out var number) ||
            number < SharedPagerSystem.MinNumber ||
            number > SharedPagerSystem.MaxNumber)
        {
            return;
        }

        string? code = null;
        var rawCode = CodeEdit.Text.Trim();
        if (!string.IsNullOrEmpty(rawCode))
        {
            if (!SharedPagerSystem.IsValidCode(rawCode))
                return;

            code = rawCode.ToUpperInvariant();
        }

        OnSend?.Invoke(number, code);
    }
}
