using System.Threading.Tasks;
using Content.Client.UserInterface.Controls;
using Content.Shared._AS.CanvasDesign;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._AS.CanvasDesign.UI;

[GenerateTypedNameReferences]
public sealed partial class CanvasDesignHistoryWindow : FancyWindow
{
    [Dependency] private IFileDialogManager _fileDialogs = null!;
    [Dependency] private IPlayerManager _players = null!;
    private CanvasDesignPreviewData? _selected;
    private CanvasDesignHistoryEntry[] _entries = [];
    private bool _showTargets;

    public event Action<int>? PreviewRequested;

    public CanvasDesignHistoryWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        HistoryList.OnItemSelected += args =>
        {
            if (HistoryList[args.ItemIndex].Metadata is int id)
            {
                PreviewRequested?.Invoke(id);
            }
        };
        HistorySearch.OnTextChanged += _ => PopulateHistory();
        ExportButton.OnPressed += async _ => await ExportSelected();
    }

    public void SetHistory(CanvasDesignHistoryEntry[] entries, CanvasDesignPreviewData? selected, bool showTargets)
    {
        _entries = entries;
        _showTargets = showTargets;
        PopulateHistory();
        SetPreview(selected);
    }

    private void PopulateHistory()
    {
        HistoryList.Clear();
        var query = HistorySearch.Text.Trim();
        foreach (var entry in _entries)
        {
            if (query.Length > 0 &&
                !entry.PreviewId.ToString().Contains(query, StringComparison.OrdinalIgnoreCase) &&
                !entry.EntityId.ToString().Contains(query, StringComparison.OrdinalIgnoreCase) &&
                !entry.SavedBy.Contains(query, StringComparison.OrdinalIgnoreCase) &&
                !entry.EntityName.Contains(query, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var text = _showTargets
                ? Loc.GetString("canvas-design-history-entry-global",
                    ("id", entry.PreviewId),
                    ("player", entry.SavedBy),
                    ("entity", entry.EntityId),
                    ("name", entry.EntityName))
                : Loc.GetString("canvas-design-history-entry",
                    ("id", entry.PreviewId),
                    ("player", entry.SavedBy));
            HistoryList.AddItem(text,
                metadata: entry.PreviewId);
        }
    }

    public void SetPreview(CanvasDesignPreviewData? selected)
    {
        _selected = selected;
        ExportButton.Disabled = selected == null;
        if (selected == null)
        {
            SignName.Text = Loc.GetString("canvas-design-history-empty");
            SavedBy.Text = string.Empty;
            ChangedAt.Text = string.Empty;
            SignDescription.SetMessage(string.Empty);
            return;
        }

        SignName.Text = selected.Name;
        SavedBy.Text = Loc.GetString("canvas-design-preview-saved-by", ("player", selected.SavedBy));
        var changedAtUtc = DateTimeOffset.FromUnixTimeSeconds(selected.SavedAt);
        // Apparently server logs use server time for log timestamps? Fucking evil?
        var changedAtServer = changedAtUtc.ToOffset(TimeSpan.FromMinutes(selected.ServerOffsetMinutes));
        ChangedAt.Text = Loc.GetString("canvas-design-preview-changed-at",
            ("utc", changedAtUtc.ToString("yyyy-MM-dd HH:mm:ss")),
            ("server", changedAtServer.ToString("yyyy-MM-dd HH:mm:ss")));
        var description = new FormattedMessage();
        if (!description.TryAddMarkup(selected.Description, out _))
            description.AddText(selected.Description);
        SignDescription.SetMessage(description);
        Canvas.Configure(selected.Width, selected.Height, selected.Background);
        Canvas.SetPixels(selected.Pixels);
    }

    private async Task ExportSelected()
    {
        if (_selected == null)
            return;

        await CanvasDesignExport.Save(_fileDialogs,
            _players.LocalSession?.Name ?? "Unknown",
            _selected.Name,
            _selected.Description,
            _selected.Width,
            _selected.Height,
            _selected.Background,
            _selected.Pixels);
    }
}
