using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._AS.CanvasDesign.UI;

[GenerateTypedNameReferences]
public sealed partial class CanvasDesignClosePrompt : DefaultWindow
{
    public event Action? SaveRequested;
    public event Action? SaveDraftRequested;
    public event Action? DiscardRequested;

    public CanvasDesignClosePrompt()
    {
        RobustXamlLoader.Load(this);
        SaveButton.OnPressed += _ => SaveRequested?.Invoke();
        SaveDraftButton.OnPressed += _ => SaveDraftRequested?.Invoke();
        NoSaveButton.OnPressed += _ => DiscardRequested?.Invoke();
        CancelButton.OnPressed += _ => Close();
        CloseButton.Visible = false;
    }
}
