using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Content.Client.Decals.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._AS.CanvasDesign;
using Content.Shared._AS.EditableMetadata;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._AS.CanvasDesign.UI;

[GenerateTypedNameReferences]
public sealed partial class CanvasDesignEditorWindow : FancyWindow
{
    private const int MaxImportBytes = 128 * 1024; // 128 KB, prevents excessively large imports that could cause performance issues or crashes.
    [Dependency] private IFileDialogManager _fileDialogs = null!;
    [Dependency] private IPlayerManager _players = null!;
    [Dependency] private ILogManager _logManager = null!;
    private readonly ISawmill _importLog;
    public event Action<CanvasPixelChange[], string, string>? SaveRequested;
    public event Action<uint[], string, string>? DraftChanged;
    public event Action? DraftDiscarded;
    private PaletteColorPicker? _palette;
    private CanvasDesignClosePrompt? _closePrompt;
    private bool _suppressChanges;
    private bool _dirty;
    private bool _allowClose;
    private int _width = 1;
    private int _height = 1;
    private uint _background = 0xFFFFFFFFu; // Default to white background
    private int _maxNameLength = ASEditableMetadataComponent.AbsoluteMaxNameLength;
    private int _maxDescriptionLength = ASEditableMetadataComponent.AbsoluteMaxDescriptionLength;
    private bool _drawingColorInitialized;
    private uint[] _savedPixels = [0xFFFFFFFFu]; // Default to white pixels

    public CanvasDesignEditorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _importLog = _logManager.GetSawmill("canvas-design.import");
        ColorSelector.SelectorType = Robust.Client.UserInterface.Controls.ColorSelectorSliders.ColorSelectorType.Hsv;
        ColorSelector.Color = Color.White;
        ColorSelector.OnColorChanged += color => Canvas.SelectedColor = color;
        Canvas.Picked += color =>
        {
            ColorSelector.Color = color;
            Canvas.SelectedColor = color;
            SetTool(CanvasDesignTool.Pencil);
        };
        PencilButton.OnPressed += _ => SetTool(CanvasDesignTool.Pencil);
        EraserButton.OnPressed += _ => SetTool(CanvasDesignTool.Eraser);
        PickerButton.OnPressed += _ => SetTool(CanvasDesignTool.Picker);
        FillButton.OnPressed += _ => SetTool(CanvasDesignTool.Fill);
        LineButton.OnPressed += _ => SetTool(CanvasDesignTool.Line);
        SquareButton.OnPressed += _ => SetTool(CanvasDesignTool.Square);
        CircleButton.OnPressed += _ => SetTool(CanvasDesignTool.Circle);
        ClearButton.OnPressed += _ => Canvas.Clear();
        ExportButton.OnPressed += async _ => await ExportDesign();
        ImportButton.OnPressed += async _ => await ImportDesign();
        ColorPalette.OnPressed += _ => TogglePalette();
        SaveButton.OnPressed += _ => SaveChanges();
        Canvas.Changed += Changed;
        NameEdit.OnTextChanged += _ =>
        {
            UpdateTextLimits();
            Changed();
        };
        DescriptionEdit.OnTextChanged += _ =>
        {
            UpdateTextLimits();
            Changed();
        };
        SetTool(CanvasDesignTool.Pencil);
        UpdateTextLimits();
    }

    public void SetState(int width,
        int height,
        uint background,
        uint defaultDrawingColor,
        bool metadataEnabled,
        int maxNameLength,
        int maxDescriptionLength,
        string editorTitle,
        uint[] pixels,
        string name,
        string description,
        string defaultName,
        string defaultDescription)
    {
        _suppressChanges = true;
        _width = width;
        _height = height;
        _background = background;
        MetadataSection.Visible = metadataEnabled;
        if (!_drawingColorInitialized)
        {
            var color = Color.FromHex($"#{defaultDrawingColor & 0xFFFFFF:X6}");
            ColorSelector.Color = color;
            Canvas.SelectedColor = color;
            _drawingColorInitialized = true;
        }
        _maxNameLength = maxNameLength;
        _maxDescriptionLength = maxDescriptionLength;
        Title = editorTitle;
        Canvas.Configure(width, height, background);
        Canvas.SetPixels(pixels);
        _savedPixels = (uint[]) pixels.Clone();
        NameEdit.PlaceHolder = defaultName;
        DescriptionEdit.Placeholder = new Rope.Leaf(defaultDescription);
        if (!NameEdit.HasKeyboardFocus())
            NameEdit.Text = name;
        if (!DescriptionEdit.HasKeyboardFocus())
            DescriptionEdit.TextRope = new Rope.Leaf(description);
        UpdateTextLimits();
        _suppressChanges = false;
        _dirty = false;
    }

    public void ApplyDraft(uint[] pixels,
        uint[] savedPixels,
        int width,
        int height,
        uint background,
        uint defaultDrawingColor,
        bool metadataEnabled,
        int maxNameLength,
        int maxDescriptionLength,
        string editorTitle,
        string name,
        string description,
        string defaultName,
        string defaultDescription)
    {
        SetState(width,
            height,
            background,
            defaultDrawingColor,
            metadataEnabled,
            maxNameLength,
            maxDescriptionLength,
            editorTitle,
            pixels,
            name,
            description,
            defaultName,
            defaultDescription);
        _savedPixels = (uint[]) savedPixels.Clone();
        _dirty = true;
    }

    public override void Close()
    {
        if (_allowClose || !_dirty)
        {
            base.Close();
            return;
        }

        if (_closePrompt?.IsOpen == true)
        {
            _closePrompt.MoveToFront();
            return;
        }

        _closePrompt = new CanvasDesignClosePrompt();
        _closePrompt.SaveRequested += () =>
        {
            SaveChanges();
            FinishClose(discard: false);
        };
        _closePrompt.SaveDraftRequested += () => FinishClose(discard: false);
        _closePrompt.DiscardRequested += () => FinishClose(discard: true);
        _closePrompt.OnClose += () => _closePrompt = null;
        _closePrompt.OpenCentered();
    }

    private void SaveChanges()
    {
        var pixels = Canvas.GetPixels();
        var changes = new List<CanvasPixelChange>();
        for (var i = 0; i < pixels.Length; i++)
        {
            if (pixels[i] != _savedPixels[i])
                changes.Add(new CanvasPixelChange((ushort) i, pixels[i]));
        }

        SaveRequested?.Invoke(changes.ToArray(), NameEdit.Text, Rope.Collapse(DescriptionEdit.TextRope));
        _savedPixels = pixels;
        _dirty = false;
    }

    private void FinishClose(bool discard)
    {
        if (discard)
            DraftDiscarded?.Invoke();

        _allowClose = true;
        _closePrompt?.Close();
        base.Close();
    }

    private void Changed()
    {
        if (_suppressChanges)
            return;

        _dirty = true;
        DraftChanged?.Invoke(Canvas.GetPixels(), NameEdit.Text, Rope.Collapse(DescriptionEdit.TextRope));
    }

    private async Task ExportDesign()
    {
        await CanvasDesignExport.Save(_fileDialogs,
            _players.LocalSession?.Name ?? "Unknown",
            NameEdit.Text,
            Rope.Collapse(DescriptionEdit.TextRope),
            _width,
            _height,
            _background,
            Canvas.GetPixels());
    }

    /// <summary>
    ///  Imports a design from a YAML file selected by the user.
    /// Validates the file's contents and applies it to the canvas if valid.
    /// </summary>
    private async Task ImportDesign()
    {
        try
        {
            await using var file = await _fileDialogs.OpenFile(access: FileAccess.Read);
            if (file == null)
                return;
            if (!file.CanSeek || file.Length > MaxImportBytes)
            {
                ImportFailed("canvas-design-import-too-large");
                return;
            }

            // Read the file contents as UTF-8 text, ensuring it does not exceed the maximum allowed size
            using var reader = new StreamReader(file, Encoding.UTF8);
            var contents = await reader.ReadToEndAsync();
            if (contents.Length > MaxImportBytes)
            {
                ImportFailed("canvas-design-import-too-large");
                return;
            }

            var lines = contents.Replace("\r", string.Empty).Split('\n');
            if (lines.Length < 6 || lines.Length > CanvasDesignComponent.MaxPixelCount * 2 + 8 ||
                !TryReadQuoted(lines[0].TrimStart('\uFEFF'), "exportedBy: ", out _) ||
                !TryReadQuoted(lines[1], "name: ", out var name) ||
                !TryReadQuoted(lines[2], "description: ", out var description) ||
                !TryReadInt(lines[3], "width: ", out var width) ||
                !TryReadInt(lines[4], "height: ", out var height))
            {
                ImportFailed("canvas-design-import-invalid-header");
                return;
            }

            // Reject oversized dimensions before performing any dimension-derived allocation or processing.
            if (!CanvasDesignComponent.DimensionsWithinLimit(width, height))
            {
                ImportFailed("canvas-design-import-invalid-dimensions");
                return;
            }

            // Validate that the imported dimensions match the current canvas dimensions. If they do not match, log an error and abort the import.
            if (width != _width || height != _height)
            {
                ImportFailed("canvas-design-import-wrong-size", ("width", _width), ("height", _height));
                return;
            }

            var pixels = new uint[_width * _height];
            Array.Fill(pixels, _background);
            var pixelStart = Array.IndexOf(lines, "pixels:") + 1;
            if (pixelStart == 0)
            {
                ImportFailed("canvas-design-import-missing-pixels");
                return;
            }

            if (!TryReadColorDictionary(lines, pixelStart, pixels, out var pixelError))
            {
                ImportFailed(pixelError ?? "canvas-design-import-invalid-pixels");
                return;
            }

            if (description.Length > _maxDescriptionLength)
                description = description[.._maxDescriptionLength];
            if (name.Length > _maxNameLength)
                name = name[.._maxNameLength];
            if (!FormattedMessage.ValidMarkup(description))
            {
                ImportFailed("canvas-design-import-invalid-markup");
                return;
            }

            // If we got here, the import was successful. Apply the imported data to the canvas.
            Canvas.SetPixels(pixels);
            NameEdit.Text = name;
            DescriptionEdit.TextRope = new Rope.Leaf(description);
            UpdateTextLimits();
            Changed();
        }
        catch (Exception)
        {
            ImportFailed("canvas-design-import-read-error");
        }
    }

    private void ImportFailed(string message, params (string, object)[] args)
    {
        _importLog.Error(Loc.GetString(message, args));
    }

    private static bool TryReadInt(string line, string prefix, out int value)
    {
        value = 0;
        return line.StartsWith(prefix) && int.TryParse(line[prefix.Length..], out value) && value > 0;
    }

    private bool TryReadColorDictionary(string[] lines, int start, uint[] pixels, out string? error)
    {
        error = null;
        var assigned = new bool[pixels.Length];
        var usedColors = new HashSet<uint>();
        uint? currentColor = null;
        var assignedCount = 0;

        for (var i = start; i < lines.Length; i++)
        {
            var line = lines[i];
            if (string.IsNullOrWhiteSpace(line))
                continue;

            if (line.StartsWith("  \"") && line.EndsWith("\":"))
            {
                var hex = line[3..^2];
                if (hex.Length != 6 ||
                    !uint.TryParse(hex, System.Globalization.NumberStyles.HexNumber, null, out var color) ||
                    color > 0xFFFFFF || !usedColors.Add(color))
                {
                    error = "canvas-design-import-invalid-color";
                    return false;
                }
                currentColor = 0xFF000000u | color;
                continue;
            }

            if (currentColor == null || !line.StartsWith("    - [") || !line.EndsWith(']'))
            {
                error = "canvas-design-import-invalid-coordinate";
                return false;
            }

            var coordinates = line[7..^1].Split(',', StringSplitOptions.TrimEntries);
            if (coordinates.Length != 2 ||
                !int.TryParse(coordinates[0], out var x) ||
                !int.TryParse(coordinates[1], out var y) ||
                x < 0 || x >= _width || y < 0 || y >= _height)
            {
                error = "canvas-design-import-invalid-coordinate";
                return false;
            }

            var index = y * _width + x;
            if (assigned[index] || ++assignedCount > pixels.Length)
            {
                error = "canvas-design-import-duplicate-coordinate";
                return false;
            }
            assigned[index] = true;
            pixels[index] = currentColor.Value;
        }

        return true;
    }

    private void UpdateTextLimits()
    {
        var nameLength = NameEdit.Text.Length;
        var descriptionLength = DescriptionEdit.TextLength;
        NameCount.Text = $"{nameLength}/{_maxNameLength}";
        DescriptionCount.Text = $"{descriptionLength}/{_maxDescriptionLength}";
        NameCount.FontColorOverride = nameLength > _maxNameLength ? Color.Red : null;
        DescriptionCount.FontColorOverride = descriptionLength > _maxDescriptionLength ? Color.Red : null;
        SaveButton.Disabled = nameLength > _maxNameLength || descriptionLength > _maxDescriptionLength;
    }

    /// Tries to read a quoted string from a line, handling escaped characters. Returns true if successful, false otherwise.
    private static bool TryReadQuoted(string line, string prefix, out string value)
    {
        value = string.Empty;
        if (!line.StartsWith(prefix + "\"") || !line.EndsWith('"'))
            return false;

        var escaped = line[(prefix.Length + 1)..^1];
        var result = new StringBuilder();
        for (var i = 0; i < escaped.Length; i++)
        {
            if (escaped[i] != '\\')
            {
                result.Append(escaped[i]);
                continue;
            }

            if (++i >= escaped.Length)
                return false;
            result.Append(escaped[i] switch
            {
                'n' => '\n',
                'r' => '\r',
                '\\' => '\\',
                '"' => '"',
                _ => escaped[i]
            });
        }

        value = result.ToString();
        return true;
    }

    private void SetTool(CanvasDesignTool tool)
    {
        Canvas.Tool = tool;
        PencilButton.Pressed = tool == CanvasDesignTool.Pencil;
        EraserButton.Pressed = tool == CanvasDesignTool.Eraser;
        PickerButton.Pressed = tool == CanvasDesignTool.Picker;
        FillButton.Pressed = tool == CanvasDesignTool.Fill;
        LineButton.Pressed = tool == CanvasDesignTool.Line;
        SquareButton.Pressed = tool == CanvasDesignTool.Square;
        CircleButton.Pressed = tool == CanvasDesignTool.Circle;
    }

    // Opens or closes the color palette window.
    private void TogglePalette()
    {
        if (_palette == null)
        {
            _palette = new PaletteColorPicker();
            _palette.OpenCenteredLeft();
            _palette.PaletteList.OnItemSelected += args =>
            {
                var color = (args.ItemList.GetSelected().First().Metadata as Color?)!.Value;
                ColorSelector.Color = color;
                Canvas.SelectedColor = color;
            };
            return;
        }

        if (_palette.IsOpen)
            _palette.Close();
        else
            _palette.Open();
    }
}
