using Content.Shared._Impstation.PersonalEconomy.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Impstation.PersonalEconomy.UI;

[GenerateTypedNameReferences]
public sealed partial class AccountInfoBox : BoxContainer
{
    public Action? OnTransactionButtonPressed;
    public Action? OnEjectPressed;
    public Action? OnDepositPressed;
    // passes amount since we want the pin to be a separate window
    public Action<int>? OnWithdrawPressed;

    private Entity<BankAccountComponent> _account;

    public AccountInfoBox()
    {
        RobustXamlLoader.Load(this);
    }

    public AccountInfoBox(Entity<BankAccountComponent> account)
    {
        RobustXamlLoader.Load(this);

        _account = account;

        TransferFundsButton.OnPressed += _ => OnTransactionButtonPressed?.Invoke();
        EjectCardButton.OnPressed += _ => OnEjectPressed?.Invoke();
        DepositButton.OnPressed += _ => OnDepositPressed?.Invoke();
        WithdrawButton.OnPressed += _ =>
        {
            if (int.TryParse(WithdrawAmountBox.Text, out var amount) && amount > 0)
            {
                OnWithdrawPressed?.Invoke(amount);
                WithdrawAmountBox.Clear();
            }
        };

        WelcomeLabel.Text = Loc.GetString("nanobank-welcome", ("name", account.Comp.Name));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        BalanceLabel.Text = Loc.GetString("nanobank-balance-amount", ("balance", $"{_account.Comp.Balance:n0}"));

        if (!NeedsInfoboxRebuild())
            return;

        TransactionInfoContainer.RemoveAllChildren();

        if (_account.Comp.Transactions.Count == 0)
        {
            TransactionInfoContainer.AddChild(new Label
            {
                Text = Loc.GetString("atm-machine-no-transactions"),
                HorizontalAlignment = HAlignment.Center,
            });
            return;
        }

        foreach (var transaction in _account.Comp.Transactions)
        {
            var infobox = new TransactionInfoBox(transaction.OtherAccount, transaction.Name, transaction.Amount, transaction.Timestamp, transaction.Reason);
            TransactionInfoContainer.AddChild(infobox);
        }
    }

    private bool NeedsInfoboxRebuild()
    {
        //for every transaction in the list, look for a matching infobox already in the container
        foreach (var transaction in _account.Comp.Transactions)
        {
            var found = false;
            foreach (var child in TransactionInfoContainer.Children)
            {
                if (child is not TransactionInfoBox infoBox)
                    continue;

                if (CompTransactionToInfobox(transaction, infoBox))
                {
                    found = true;
                    break;
                }
            }

            if (!found)
                return true;
        }

        return false;
    }

    private bool CompTransactionToInfobox(BankTransaction transaction, TransactionInfoBox infoBox)
    {
        return transaction.OtherAccount == infoBox.Other &&
               transaction.Amount == infoBox.Amount &&
               // ReSharper disable once CompareOfFloatsByEqualityOperator - we only care if the timestamps are literally identical
               transaction.Timestamp == infoBox.Timestamp &&
               transaction.Reason == infoBox.Reason;
    }
}
