using Content.Client.UserInterface.Controls;
using Content.Shared._Impstation.PersonalEconomy.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Impstation.PersonalEconomy.UI;

[GenerateTypedNameReferences]
public sealed partial class ATMMenu : FancyWindow
{
    public Action? OnTransactionButtonPressed;
    public Action? OnInsertCardPressed;
    public Action? OnEjectCardPressed;
    public Action? OnDepositPressed;
    public Action<int>? OnWithdrawPressed;

    public Func<Entity<BankAccountComponent>?>? GetInsertedAccount;
    // true when a card is in the slot, regardless of whether it has an account
    public Func<bool>? IsCardInserted;

    private EntityUid? _shownAccount;
    private NoAccountInfoBox? _noAccountBox;

    public ATMMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CreateInvalidInfoBox();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        var inserted = GetInsertedAccount?.Invoke();

        if (inserted == null)
        {
            if (_noAccountBox == null)
                CreateInvalidInfoBox();

            _noAccountBox?.SetUnprogrammed(IsCardInserted?.Invoke() ?? false);
            return;
        }

        if (_shownAccount == inserted.Value.Owner)
            return;

        CreateInfoBoxForAccount(inserted.Value);
    }

    public void CreateInvalidInfoBox()
    {
        ClearInfoBox();

        _noAccountBox = new NoAccountInfoBox();
        _noAccountBox.OnInsertCardPressed += () => OnInsertCardPressed?.Invoke();
        _noAccountBox.OnEjectCardPressed += () => OnEjectCardPressed?.Invoke();
        AccountInfoContainer.AddChild(_noAccountBox);
    }

    public void CreateInfoBoxForAccount(Entity<BankAccountComponent> account)
    {
        ClearInfoBox();

        var infobox = new AccountInfoBox(account);
        infobox.OnTransactionButtonPressed += () => OnTransactionButtonPressed?.Invoke();
        infobox.OnEjectPressed += () => OnEjectCardPressed?.Invoke();
        infobox.OnDepositPressed += () => OnDepositPressed?.Invoke();
        infobox.OnWithdrawPressed += amount => OnWithdrawPressed?.Invoke(amount);
        AccountInfoContainer.AddChild(infobox);
        _shownAccount = account.Owner;
    }

    public void ClearInfoBox()
    {
        AccountInfoContainer.RemoveAllChildren();
        _shownAccount = null;
        _noAccountBox = null;
    }
}
