using Content.Client.UserInterface.Controls;
using Content.Shared._Impstation.PersonalEconomy.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Impstation.PersonalEconomy.UI;

[GenerateTypedNameReferences]
public sealed partial class CurrencyExchangeMenu : FancyWindow
{
    public Action? OnInsertPressed;
    public Action? OnEjectPressed;
    public Action? OnConvertPressed;

    public Func<(int Count, bool IsScrip, int Tax, int ScripPerSpeso)?>? GetState;

    public CurrencyExchangeMenu()
    {
        RobustXamlLoader.Load(this);

        InsertButton.OnPressed += _ => OnInsertPressed?.Invoke();
        EjectButton.OnPressed += _ => OnEjectPressed?.Invoke();
        ConvertButton.OnPressed += _ => OnConvertPressed?.Invoke();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        var state = GetState?.Invoke();

        if (state == null)
        {
            RateLabel.Text = string.Empty;
            SlotLabel.Text = Loc.GetString("currency-exchange-empty");
            PreviewLabel.Text = string.Empty;
            InsertButton.Disabled = false;
            EjectButton.Disabled = true;
            ConvertButton.Disabled = true;
            return;
        }

        var (count, isScrip, tax, scripPerSpeso) = state.Value;
        var inName = Loc.GetString(isScrip ? "currency-exchange-scrip" : "currency-exchange-spesos");
        var outName = Loc.GetString(isScrip ? "currency-exchange-spesos" : "currency-exchange-scrip");
        var payout = CurrencyExchangeComponent.ComputeConversion(count, isScrip, tax, scripPerSpeso);

        RateLabel.Text = Loc.GetString("currency-exchange-rate", ("tax", tax));
        SlotLabel.Text = Loc.GetString("currency-exchange-inserted", ("count", count), ("currency", inName));
        PreviewLabel.Text = Loc.GetString("currency-exchange-preview", ("amount", payout), ("currency", outName));
        InsertButton.Disabled = true;
        EjectButton.Disabled = false;
        ConvertButton.Disabled = payout <= 0;
    }
}
