using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI;

[GenerateTypedNameReferences]
public sealed partial class PinEntryMenu : FancyWindow
{
    public Action<int>? OnPinEntered;

    public PinEntryMenu()
    {
        RobustXamlLoader.Load(this);

        PinKeypad.OnEnterButtonPressed += s =>
        {
            if (int.TryParse(s, out var pin))
                OnPinEntered?.Invoke(pin);
            Close();
        };
    }

    public void Reset()
    {
        PinKeypad.SetEnteredNumber("");
    }
}
