using Content.Shared._Impstation.PersonalEconomy.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI;

[GenerateTypedNameReferences]
public sealed partial class TransactionInfoBox : Control
{
    public readonly AccountNumber Other;
    public readonly string OtherName = "";
    public readonly int Amount;
    public readonly double Timestamp;
    public readonly string Reason = "";

    public TransactionInfoBox()
    {
        RobustXamlLoader.Load(this);
    }

    public TransactionInfoBox(AccountNumber other, string name, int amount, double timestamp, string reason)
    {
        RobustXamlLoader.Load(this);

        Other = other;
        OtherName = name;
        Amount = amount;
        Timestamp = timestamp;
        Reason = reason;

        DescriptionLabel.Text = !string.IsNullOrWhiteSpace(reason)
            ? reason
            : Loc.GetString("nanobank-transaction-counterparty", ("name", name), ("number", $"{other.Number:000000}"));

        var signed = amount < 0
            ? Loc.GetString("nanobank-transaction-amount-out", ("amount", $"{int.Abs(amount):n0}"))
            : Loc.GetString("nanobank-transaction-amount-in", ("amount", $"{amount:n0}"));
        AmountLabel.Text = signed;

        CategoryLabel.Text = Loc.GetString(amount < 0 ? "nanobank-category-purchase" : "nanobank-category-deposit");

        ToolTip = amount < 0
            ? Loc.GetString("nanobank-transaction-tooltip-out", ("name", name), ("number", $"{other.Number:000000}"), ("amount", int.Abs(amount)), ("reason", reason))
            : Loc.GetString("nanobank-transaction-tooltip-in", ("name", name), ("number", $"{other.Number:000000}"), ("amount", amount), ("reason", reason));
    }
}
