using Content.Shared._Funkystation.Unions;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;

namespace Content.Client._Funkystation.Unions.UI;

[GenerateTypedNameReferences]
public sealed partial class MegaphoneMenu : DefaultWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;

    public event Action<string>? OnCallStrike;

    private bool _onStrike;

    public MegaphoneMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        MessageEdit.Placeholder = new Rope.Leaf(Loc.GetString("megaphone-message-placeholder"));
        MessageEdit.OnTextChanged += _ => SyncButtonState();

        CallStrikeButton.OnPressed += _ =>
        {
            OnCallStrike?.Invoke(Rope.Collapse(MessageEdit.TextRope));
        };

        SyncButtonState();
    }

    public void UpdateState(MegaphoneBoundUserInterfaceState state)
    {
        _onStrike = state.OnStrike;
        SyncButtonState();
    }

    private void SyncButtonState()
    {
        CallStrikeButton.Text = Loc.GetString(_onStrike ? "megaphone-end-strike-button" : "megaphone-call-strike-button");

        var maxLength = _cfg.GetCVar(CCVars.ChatMaxAnnouncementLength);
        if (MessageEdit.TextLength > maxLength)
        {
            CallStrikeButton.Disabled = true;
            CallStrikeButton.ToolTip = Loc.GetString("megaphone-message-too-long");
        }
        else
        {
            CallStrikeButton.Disabled = false;
            CallStrikeButton.ToolTip = null;
        }
    }
}
