using Content.Shared._Funkystation.Unions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.Unions.UI;

[GenerateTypedNameReferences]
public sealed partial class UnionNoteEntry : BoxContainer
{
    public UnionNoteEntry(UnionClipboardNoteEntry note)
    {
        RobustXamlLoader.Load(this);

        TitleLabel.Text = note.Title;
        MetaLabel.Text = $"{note.Author} - {note.Time}";
        TextLabel.SetMessage(note.Text);
    }
}
