using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;

namespace Content.Client._Funkystation.Unions.UI;

[GenerateTypedNameReferences]
public sealed partial class UnionClipboardMenu : BaseWindow
{
    
}