using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client._Funkystation.Unions.UI;

[GenerateTypedNameReferences]
public sealed partial class UnionMemberRow : BoxContainer
{
    public event Action? OnRemovePressed;
    public event Action? OnNotesPressed;
    public event Action? OnMakeStewardPressed;
    public event Action<NetEntity?>? OnStewardAssigned;

    public UnionMemberRow(string name, string jobTitle, bool isLeader, bool isSteward, List<(NetEntity Entity, string Name)> stewards, NetEntity? assignedSteward)
    {
        RobustXamlLoader.Load(this);

        NameLabel.Text = isLeader
            ? Loc.GetString("union-clipboard-leader-name", ("name", name))
            : isSteward
                ? Loc.GetString("union-clipboard-steward-name", ("name", name))
                : name;
        JobLabel.Text = jobTitle;
        RemoveButton.Disabled = isLeader;
        StewardButton.Visible = !isLeader;
        StewardButton.Disabled = isSteward;

        RemoveButton.OnPressed += _ => OnRemovePressed?.Invoke();
        NotesButton.OnPressed += _ => OnNotesPressed?.Invoke();
        StewardButton.OnPressed += _ => OnMakeStewardPressed?.Invoke();

        AssignRow.Visible = !isLeader && !isSteward && stewards.Count > 0;

        if (AssignRow.Visible)
        {
            StewardAssignOption.AddItem(Loc.GetString("union-clipboard-assign-steward-none"), 0);

            var selectedId = 0;
            for (var i = 0; i < stewards.Count; i++)
            {
                var id = i + 1;
                StewardAssignOption.AddItem(stewards[i].Name, id);
                if (assignedSteward == stewards[i].Entity)
                    selectedId = id;
            }

            StewardAssignOption.SelectId(selectedId);

            StewardAssignOption.OnItemSelected += args =>
            {
                StewardAssignOption.SelectId(args.Id);
                OnStewardAssigned?.Invoke(args.Id == 0 ? null : stewards[args.Id - 1].Entity);
            };
        }
    }
}
