using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Funkystation.Unions.UI;

[GenerateTypedNameReferences]
public sealed partial class UnionAddNoteMenu : DefaultWindow
{
    public event Action<string, string>? OnSubmit;

    public UnionAddNoteMenu()
    {
        RobustXamlLoader.Load(this);

        SubmitButton.OnPressed += _ =>
        {
            var title = TitleEdit.Text.Trim();
            var text = Rope.Collapse(TextEditBox.TextRope).Trim();

            if (title.Length == 0 || text.Length == 0)
                return;

            OnSubmit?.Invoke(title, text);
            Close();
        };
    }
}
