using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.Unions.UI;

[GenerateTypedNameReferences]
public sealed partial class UnionClipboardClaimMenu : DefaultWindow
{
    public event Action? OnConfirm;

    public UnionClipboardClaimMenu()
    {
        RobustXamlLoader.Load(this);

        YesButton.OnPressed += _ =>
        {
            OnConfirm?.Invoke();
            Close();
        };

        NoButton.OnPressed += _ => Close();
    }
}
