using Content.Shared._Funkystation.Unions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.Unions.UI;

[GenerateTypedNameReferences]
public sealed partial class UnionMemberNotesMenu : DefaultWindow
{
    public event Action? OnAddNoteRequested;

    public UnionMemberNotesMenu(string memberName, List<UnionClipboardNoteEntry> notes)
    {
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("union-clipboard-notes-window-title", ("name", memberName));

        AddNoteButton.OnPressed += _ => OnAddNoteRequested?.Invoke();

        Populate(notes);
    }

    public void Populate(List<UnionClipboardNoteEntry> notes)
    {
        NoteList.RemoveAllChildren();

        if (notes.Count == 0)
        {
            NoteList.AddChild(new Label { Text = Loc.GetString("union-clipboard-no-notes"), FontColorOverride = Color.Gray });
            return;
        }

        foreach (var note in notes)
        {
            NoteList.AddChild(new UnionNoteEntry(note));
        }
    }
}
