using Content.Shared._Funkystation.Unions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client._Funkystation.Unions.UI;

[GenerateTypedNameReferences]
public sealed partial class UnionClipboardMenu : DefaultWindow
{
    public event Action<NetEntity>? OnRemoveMember;
    public event Action<NetEntity, string, string>? OnAddNote;
    public event Action<NetEntity>? OnBeginSteward;
    public event Action? OnCancelSteward;

    private UnionMemberNotesMenu? _notesMenu;
    private NetEntity _notesMenuTarget;

    public UnionClipboardMenu()
    {
        RobustXamlLoader.Load(this);

        LockedCancelButton.OnPressed += _ => OnCancelSteward?.Invoke();
    }

    public void UpdateState(UnionClipboardBoundUserInterfaceState state)
    {
        Title = state.UnionName;

        if (state.LockedForName is { } lockedName)
        {
            MemberListScroll.Visible = false;
            LockedContainer.Visible = true;
            LockedLabel.SetMessage(Loc.GetString("union-clipboard-locked-message", ("name", lockedName)));
            return;
        }

        MemberListScroll.Visible = true;
        LockedContainer.Visible = false;

        MemberList.RemoveAllChildren();

        foreach (var member in state.Members)
        {
            var row = new UnionMemberRow(member.Name, member.JobTitle, member.IsLeader, member.IsSteward);
            row.OnRemovePressed += () => OnRemoveMember?.Invoke(member.Entity);
            row.OnNotesPressed += () => OpenNotes(member);
            row.OnMakeStewardPressed += () => OnBeginSteward?.Invoke(member.Entity);
            MemberList.AddChild(row);

            if (_notesMenu != null && _notesMenuTarget == member.Entity)
                _notesMenu.Populate(member.Notes);
        }
    }

    private void OpenNotes(UnionClipboardMemberEntry member)
    {
        if (_notesMenu != null && _notesMenuTarget == member.Entity)
        {
            _notesMenu.MoveToFront();
            return;
        }

        _notesMenu?.Close();

        _notesMenuTarget = member.Entity;
        _notesMenu = new UnionMemberNotesMenu(member.Name, member.Notes);
        _notesMenu.OnClose += () => _notesMenu = null;
        _notesMenu.OnAddNoteRequested += () =>
        {
            var addNote = new UnionAddNoteMenu();
            addNote.OnSubmit += (title, text) => OnAddNote?.Invoke(member.Entity, title, text);
            addNote.OpenCentered();
        };

        _notesMenu.OpenCentered();
    }
}
