using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.Unions.UI;

[GenerateTypedNameReferences]
public sealed partial class UnionClipboardMenu : DefaultWindow
{
    public UnionClipboardMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void AddMember(Control entry)
    {
        MemberList.AddChild(entry);
    }

    public void ClearMembers()
    {
        MemberList.RemoveAllChildren();
    }
}
