using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.Unions.UI;

[GenerateTypedNameReferences]
public sealed partial class UnionMemberRow : BoxContainer
{
    public event Action? OnRemovePressed;
    public event Action? OnNotesPressed;

    public UnionMemberRow(string name, string jobTitle, bool isLeader)
    {
        RobustXamlLoader.Load(this);

        NameLabel.Text = isLeader ? Loc.GetString("union-clipboard-leader-name", ("name", name)) : name;
        JobLabel.Text = jobTitle;
        RemoveButton.Disabled = isLeader;

        RemoveButton.OnPressed += _ => OnRemovePressed?.Invoke();
        NotesButton.OnPressed += _ => OnNotesPressed?.Invoke();
    }
}
