using Content.Client.UserInterface.Controls;
using Content.Shared._Funkystation.SM;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.SM;

[GenerateTypedNameReferences]
public sealed partial class SupermatterConsoleWindow : FancyWindow
{
    public SupermatterConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(SupermatterConsoleBoundUserInterfaceState state)
    {
        if (!state.HasActiveCrystal)
        {
            StatusLabel.SetMessage(Loc.GetString("supermatter-console-no-crystal"));
            IntegrityLabel.Visible = false;
            PowerLabel.Visible = false;
            AbsorbedLabel.Visible = false;
            PredictedDelamLabel.Visible = false;
            DelamLabel.Visible = false;
            return;
        }

        StatusLabel.SetMessage(Loc.GetString("supermatter-console-linked"));
        IntegrityLabel.Visible = true;
        IntegrityLabel.SetMessage(Loc.GetString("supermatter-console-integrity",
            ("percent", float.Round(state.IntegrityPercent, 1)),
            ("current", (int) state.Integrity),
            ("max", (int) state.MaxIntegrity)));
        PowerLabel.Visible = true;
        PowerLabel.SetMessage(Loc.GetString("supermatter-console-internal-energy",
            ("mev", (int) state.InternalEnergyMeV)));
        AbsorbedLabel.Visible = true;
        AbsorbedLabel.SetMessage(Loc.GetString("supermatter-console-absorbed-moles",
            ("moles", float.Round(state.AbsorbedTotalMoles, 1))));
        PredictedDelamLabel.Visible = true;
        PredictedDelamLabel.SetMessage(Loc.GetString("supermatter-console-predicted-delam",
            ("type", Loc.GetString($"supermatter-console-delam-type-{(DelamType)state.PredictedDelamType}"))));
        if (state.Delamming)
        {
            DelamLabel.Visible = true;
            DelamLabel.SetMessage(Loc.GetString("supermatter-console-delamming-countdown",
                ("seconds", float.Round(state.DelamCountdown, 1))));
        }
        else
        {
            DelamLabel.Visible = false;
        }
    }
}
