# Partial prototypes start

# TODO: Move other modifications we made to the protos here

- type: chameleonOutfit
  id: ParamedicChameleonOutfit
  equipment:
    eyes: ClothingEyesGlassesCheapSunglasses

# Partial prototypes end
