using System.Collections.Generic;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Content.Shared._Impstation.PersonalEconomy.Components;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Impstation.PersonalEconomy.UI.AccountManagement;

[GenerateTypedNameReferences]
public sealed partial class AccountManagementMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = null!;
    [Dependency] private readonly IPrototypeManager _protoMan = null!;
    [Dependency] private readonly IGameTiming _timing = null!;
    [Dependency] private readonly IConfigurationManager _cfg = null!;

    private readonly ClientBankingSystem _banking;

    public Action<AccountNumber, PaymentStatus, string>? OnSetStatus;
    public Action<AccountNumber, int>? OnSetSalary;
    public Action<AccountNumber, int>? OnGrantBonus;
    public Action? OnInsertCard;
    public Action? OnEjectCard;
    public Action<AccountNumber>? OnWriteCard;
    public Action<string>? OnCreateAccount;
    public Action<string, PaymentStatus, string>? OnSetDepartmentStatus;
    public Action<string, int>? OnGrantDepartmentBonus;
    public Action<int>? OnCashOut;

    public Func<BankCardComponent?>? GetInsertedCard;
    public Func<StationPayrollComponent?>? GetPayroll;

    private readonly Dictionary<int, CrewPaymentRow> _rows = new();
    private readonly Dictionary<string, DepartmentRow> _deptRows = new();
    private AccountNumber? _selected;

    public AccountManagementMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _banking = _entMan.System<ClientBankingSystem>();

        ToggleStatusButton.OnPressed += _ => ToggleStatus();
        SetPayButton.OnPressed += _ => SetSalary();
        GrantBonusButton.OnPressed += _ => GrantBonus();

        AccountsTabButton.OnPressed += _ => ShowDepartments(false);
        DepartmentsTabButton.OnPressed += _ => ShowDepartments(true);

        SearchBar.OnTextChanged += _ => ApplyFilter();
        ProgramCardButton.OnPressed += _ => ShowCardView(true);
        CardBackButton.OnPressed += _ => ShowCardView(false);
        CardInsertButton.OnPressed += _ => OnInsertCard?.Invoke();
        CardEjectButton.OnPressed += _ => OnEjectCard?.Invoke();
        WriteCardButton.OnPressed += _ =>
        {
            if (_selected != null)
                OnWriteCard?.Invoke(_selected.Value);
        };
        CreateAccountButton.OnPressed += _ =>
        {
            var name = NewAccountNameEdit.Text.Trim();
            if (name.Length == 0)
                return;

            OnCreateAccount?.Invoke(name);
            NewAccountNameEdit.Clear();
        };

        CashOutButton.OnPressed += _ => ShowCashOut(true);
        CashOutBackButton.OnPressed += _ => ShowCashOut(false);
        CashOutConfirmButton.OnPressed += _ =>
        {
            if (int.TryParse(CashOutAmountBox.Text, out var amount) && amount > 0)
            {
                OnCashOut?.Invoke(amount);
                CashOutAmountBox.Clear();
            }
        };

        FooterLabel.Text = Loc.GetString("account-management-window-title");
        ShowDetail(null);
        ShowDepartments(false);
        ShowCardView(false);
        ShowCashOut(false);
    }

    private void ShowCardView(bool card)
    {
        CashOutView.Visible = false;
        CardView.Visible = card;
        MainView.Visible = !card;
    }

    private void ShowCashOut(bool cash)
    {
        CardView.Visible = false;
        CashOutView.Visible = cash;
        MainView.Visible = !cash;
    }

    private void ShowDepartments(bool departments)
    {
        AccountsView.Visible = !departments;
        DepartmentsView.Visible = departments;
        AccountsTabButton.Pressed = !departments;
        DepartmentsTabButton.Pressed = departments;

        MidSeparator.Visible = !departments;
        DetailContainer.Visible = !departments;
        RightSeparator.Visible = !departments;
        RecordsColumn.Visible = !departments;
    }

    // rebuilds both the account list and the department list. only happens on open
    public void Populate()
    {
        CrewListContainer.RemoveAllChildren();
        DeptListContainer.RemoveAllChildren();
        _rows.Clear();
        _deptRows.Clear();

        var departments = new HashSet<string>();

        var query = _entMan.EntityQueryEnumerator<BankAccountComponent>();
        while (query.MoveNext(out var uid, out var comp))
        {
            //the station's own scrip pool isn't a crew member
            if (comp.IsStationAccount)
                continue;

            var row = new CrewPaymentRow((uid, comp));
            row.OnPressed += Select;
            CrewListContainer.AddChild(row);
            _rows[comp.AccountNumber] = row;

            if (comp.Department.Length != 0)
                departments.Add(comp.Department);
        }

        BuildDeptList(departments);
        ApplyFilter();
    }

    private void BuildDeptList(HashSet<string> departments)
    {
        foreach (var dept in departments)
        {
            var name = _protoMan.TryIndex<DepartmentPrototype>(dept, out var proto)
                ? Loc.GetString(proto.Name)
                : dept;

            var row = new DepartmentRow(dept, name);
            row.OnToggleStatus += (department, anyEligible) =>
            {
                var target = anyEligible ? PaymentStatus.Suspended : PaymentStatus.Eligible;
                OnSetDepartmentStatus?.Invoke(department, target, string.Empty);
            };
            row.OnGrantBonus += (department, amount) => OnGrantDepartmentBonus?.Invoke(department, amount);
            DeptListContainer.AddChild(row);
            _deptRows[dept] = row;
        }
    }

    // filters the account list by name or number
    private void ApplyFilter()
    {
        var search = SearchBar.Text.Trim();
        foreach (var (access, row) in _rows)
        {
            if (search.Length == 0)
            {
                row.Visible = true;
                continue;
            }

            var name = _banking.TryGetAccount(access, out var ent) ? ent.Value.Comp.Name : string.Empty;
            row.Visible = name.Contains(search, StringComparison.OrdinalIgnoreCase)
                || $"{access:000000}".Contains(search);
        }
    }

    private void Select(AccountNumber account)
    {
        _selected = account;
        if (_banking.TryGetAccount(account, out var ent))
            ShowDetail(ent.Value.Comp);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        if (CardView.Visible)
        {
            UpdateCardView();
            return;
        }

        if (CashOutView.Visible)
        {
            UpdateCashOutView();
            return;
        }

        // keep the list statuses and the open detail panel live
        foreach (var (access, row) in _rows)
        {
            if (_banking.TryGetAccount(access, out var ent))
                row.Update(ent.Value.Comp);
        }

        if (_selected != null && _banking.TryGetAccount(_selected.Value, out var sel))
            ShowDetail(sel.Value.Comp);
        else if (_selected != null)
            ShowDetail(null);

        UpdateDeptRows();
        UpdateStationHeader();

        // hide the cash-out entry point when the feature is disabled
        CashOutButton.Visible = _cfg.GetCVar(CCVars.ScripStationCashout);
    }

    private void UpdateStationHeader()
    {
        var payroll = GetPayroll?.Invoke();
        if (payroll == null || payroll.StationAccount.Number == 0)
        {
            StationBalanceLabel.Text = Loc.GetString("nanobank-placeholder");
            NextCycleLabel.Text = Loc.GetString("nanobank-placeholder");
            return;
        }

        StationBalanceLabel.Text = _banking.TryGetAccount(payroll.StationAccount, out var acc)
            ? Loc.GetString("nanobank-balance-amount", ("balance", $"{acc.Value.Comp.Balance:n0}"))
            : Loc.GetString("nanobank-placeholder");

        // countdown to the next cycle
        var remaining = payroll.NextPayout - _timing.CurTime;
        if (remaining < TimeSpan.Zero)
            remaining = TimeSpan.Zero;
        NextCycleLabel.Text = $"{remaining:hh\\:mm\\:ss}";
    }

    private void UpdateCashOutView()
    {
        var balance = 0;
        var payroll = GetPayroll?.Invoke();
        if (payroll != null && _banking.TryGetAccount(payroll.StationAccount, out var acc))
            balance = acc.Value.Comp.Balance;

        var rate = AccountManagementConsoleComponent.CashoutRate;
        CashOutBalanceLabel.Text = Loc.GetString("nanobank-cash-out-balance", ("balance", $"{balance:n0}"));
        CashOutRateLabel.Text = Loc.GetString("nanobank-cash-out-rate", ("rate", rate));

        var spesos = int.TryParse(CashOutAmountBox.Text, out var amount) && amount > 0
            ? amount / rate
            : 0;
        CashOutPreviewLabel.Text = Loc.GetString("nanobank-cash-out-preview", ("amount", spesos));
    }

    // each department row's toggle reflects whether anyone in it is still eligible
    private void UpdateDeptRows()
    {
        foreach (var (dept, row) in _deptRows)
        {
            var anyEligible = false;
            var query = _entMan.EntityQueryEnumerator<BankAccountComponent>();
            while (query.MoveNext(out _, out var comp))
            {
                if (comp.Department == dept && comp.Status == PaymentStatus.Eligible)
                {
                    anyEligible = true;
                    break;
                }
            }
            row.SetEligible(anyEligible);
        }
    }

    private void UpdateCardView()
    {
        // which account are we writing
        string targetName;
        if (_selected != null && _banking.TryGetAccount(_selected.Value, out var acc))
        {
            targetName = string.IsNullOrWhiteSpace(acc.Value.Comp.Name)
                ? Loc.GetString("nanobank-unknown-account")
                : acc.Value.Comp.Name;
        }
        else
        {
            targetName = Loc.GetString("nanobank-no-account-selected");
        }
        CardTargetLabel.Text = Loc.GetString("nanobank-card-target", ("name", targetName));

        // is there a card in the slot
        var card = GetInsertedCard?.Invoke();
        CardSlotLabel.Text = card == null
            ? Loc.GetString("nanobank-card-slot-empty")
            : Loc.GetString("nanobank-card-slot-filled");

        CardInsertButton.Disabled = card != null;
        CardEjectButton.Disabled = card == null;
        // can only write with both a card present and an account selected
        WriteCardButton.Disabled = card == null || _selected == null;
        // a new business account just needs a card to write onto
        CreateAccountButton.Disabled = card == null;
    }

    private void ShowDetail(BankAccountComponent? comp)
    {
        var has = comp != null;
        ToggleStatusButton.Disabled = !has;
        SetPayButton.Disabled = !has;
        GrantBonusButton.Disabled = !has;
        StatusReasonEdit.Editable = has;
        SalaryEdit.Editable = has;
        BonusEdit.Editable = has;

        if (!has)
        {
            DetailStatusLabel.Text = Loc.GetString("nanobank-placeholder");
            DetailStatusLabel.StyleClasses.Clear();
            ToggleStatusButton.Text = Loc.GetString("nanobank-set-suspended-button");
            DetailPayLabel.Text = Loc.GetString("nanobank-placeholder");
            RecordsContainer.RemoveAllChildren();
            return;
        }

        var suspended = comp!.Status == PaymentStatus.Suspended;
        DetailStatusLabel.Text = Loc.GetString(suspended ? "nanobank-status-suspended" : "nanobank-status-eligible");
        DetailStatusLabel.StyleClasses.Clear();
        DetailStatusLabel.StyleClasses.Add(suspended ? "Danger" : "Good");

        // button shows the status it'll switch to
        ToggleStatusButton.Text = Loc.GetString(suspended ? "nanobank-set-eligible-button" : "nanobank-set-suspended-button");

        DetailPayLabel.Text = Loc.GetString("nanobank-pay-per-cycle", ("amount", $"{comp.Salary:n0}"));

        RebuildRecords(comp);
    }

    private void RebuildRecords(BankAccountComponent comp)
    {
        RecordsContainer.RemoveAllChildren();
        foreach (var t in comp.Transactions)
        {
            RecordsContainer.AddChild(new TransactionInfoBox(t.OtherAccount, t.Name, t.Amount, t.Timestamp, t.Reason));
        }
    }

    private void ToggleStatus()
    {
        if (_selected == null || !_banking.TryGetAccount(_selected.Value, out var ent))
            return;

        var next = ent.Value.Comp.Status == PaymentStatus.Suspended
            ? PaymentStatus.Eligible
            : PaymentStatus.Suspended;
        OnSetStatus?.Invoke(_selected.Value, next, StatusReasonEdit.Text);
    }

    private void SetSalary()
    {
        if (_selected == null || !int.TryParse(SalaryEdit.Text, out var salary) || salary < 0)
            return;

        OnSetSalary?.Invoke(_selected.Value, salary);
        SalaryEdit.Clear();
    }

    private void GrantBonus()
    {
        if (_selected == null || !int.TryParse(BonusEdit.Text, out var amount) || amount <= 0)
            return;

        OnGrantBonus?.Invoke(_selected.Value, amount);
        BonusEdit.Clear();
    }
}
