using Content.Shared._Impstation.PersonalEconomy.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI.AccountManagement;

[GenerateTypedNameReferences]
public sealed partial class CrewPaymentRow : Control
{
    public readonly AccountNumber Account;
    public Action<AccountNumber>? OnPressed;

    public CrewPaymentRow()
    {
        RobustXamlLoader.Load(this);
    }

    public CrewPaymentRow(Entity<BankAccountComponent> account)
    {
        RobustXamlLoader.Load(this);

        Account = account.Comp.AccountNumber;
        SelectButton.OnPressed += _ => OnPressed?.Invoke(Account);

        Update(account.Comp);
    }

    public void Update(BankAccountComponent comp)
    {
        NameLabel.Text = string.IsNullOrWhiteSpace(comp.Name)
            ? Loc.GetString("nanobank-unknown-account")
            : comp.Name;

        var suspended = comp.Status == PaymentStatus.Suspended;
        StatusLabel.Text = Loc.GetString(suspended ? "nanobank-status-suspended" : "nanobank-status-eligible");
        StatusLabel.StyleClasses.Clear();
        StatusLabel.StyleClasses.Add(suspended ? "Danger" : "Good");
    }
}
