using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.PersonalEconomy.UI.AccountManagement;

[GenerateTypedNameReferences]
public sealed partial class DepartmentRow : Control
{
    public readonly string Department;

    public Action<string, bool>? OnToggleStatus;
    public Action<string, int>? OnGrantBonus;

    private bool _anyEligible = true;

    public DepartmentRow()
    {
        RobustXamlLoader.Load(this);
        Department = string.Empty;
    }

    public DepartmentRow(string department, string label)
    {
        RobustXamlLoader.Load(this);

        Department = department;
        NameLabel.Text = label;

        StatusButton.OnPressed += _ => OnToggleStatus?.Invoke(Department, _anyEligible);
        BonusButton.OnPressed += _ =>
        {
            if (int.TryParse(BonusEdit.Text, out var amount) && amount > 0)
            {
                OnGrantBonus?.Invoke(Department, amount);
                BonusEdit.Clear();
            }
        };
    }

    // anyEligible drives whether the toggle suspends or resumes the department
    public void SetEligible(bool anyEligible)
    {
        _anyEligible = anyEligible;
        StatusButton.Text = Loc.GetString(anyEligible ? "nanobank-suspend-dept-button" : "nanobank-resume-dept-button");
    }
}
