# SPDX-FileCopyrightText: 2026 ThatOneMoon <juozas.dringelis@gmail.com>
# SPDX-License-Identifier: MIT

- type: entity
  id: CargoTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: cargo techfab machine board
  description: A machine printed circuit board for a cargo techfab.
  components:
  - type: Sprite
    state: supply
  - type: MachineBoard
    prototype: CargoTechFab
    stackRequirements:
      Manipulator: 4
    tagRequirements:
      GlassBeaker:
        amount: 2
        defaultPrototype: Beaker