using System.Globalization;
using Content.Shared.Atmos.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;
using Content.Shared.Atmos;
using Content.Client.Atmos.EntitySystems;
using System.Runtime.CompilerServices;
using DependencyAttribute = Robust.Shared.IoC.DependencyAttribute;
using Content.Shared.Atmos.Piping.Trinary.Components;
using Robust.Shared.Player;

namespace Content.Client.Atmos.UI
{
    /// <summary>
    /// Client-side UI used to control a gas filter.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class GasFilterWindow : DefaultWindow
    {
        private readonly ButtonGroup _buttonGroup = new();

        public List<string> SelectedGases = new(); // Funky - Allow multiple gases to be filtered

        public event Action<bool>? ToggleStatusButtonPressed;
        public event Action<string>? FilterTransferRateChanged;
        public event Action? SelectGasPressed;

        // funky - start
        private Button _selectAll => CSelectAll;
        private Button _deselectAll => CDeselectAll;

        private GridContainer _gases => CGasContainer;

        private Dictionary<string, Button> _gasControls = new();

        // funky - end
        public GasFilterWindow()
        {
            RobustXamlLoader.Load(this);

            ToggleStatusButton.OnToggled += _ => ToggleStatusButtonPressed?.Invoke(ToggleStatusButton.Pressed);

            FilterTransferRateInput.OnTextChanged += _ => SetFilterRate.Disabled = false;
            SetFilterRate.OnPressed += _ =>
            {
                FilterTransferRateChanged?.Invoke(FilterTransferRateInput.Text);
                SetFilterRate.Disabled = true;
            };


        }

        public void SetTransferRate(float rate)
        {
            FilterTransferRateInput.Text = rate.ToString(CultureInfo.CurrentCulture);
        }

        public void SetFilterStatus(bool enabled)
        {
            ToggleStatusButton.Pressed = enabled;
        }



        public void PopulateGasList(IEnumerable<GasPrototype> gases, GasFilterComponent filter)
        {
            SelectedGases = filter.FilteredGases.Select(gas => gas.ToString()).ToList();

            // funky - start
            _selectAll.OnPressed += _ =>
            {
                SelectedGases = gases.Select(gas => gas.ID).ToList();
                GasSelected(filter);
                SetSelectedGases(filter);
            };
            _deselectAll.OnPressed += _ =>
            {
                SelectedGases.Clear();
                GasSelected(filter);
                SetSelectedGases(filter);
            };


            foreach (var gas in gases)
            {
                var gasName = gas.Name;
                if (!Enum.TryParse<Gas>(gas.ID, out var gasEnum)) continue;

                var gasButton = new Button
                {
                    Name = gas.ID,
                    Text = Loc.GetString(gasName),
                    ToggleMode = true,
                    HorizontalExpand = true,
                    Pressed = filter.FilteredGases.Contains(gasEnum)
                };

                gasButton.OnToggled += args =>
                {
                    if (args.Pressed)
                        SelectedGases.Add(gas.ID);
                    else
                        SelectedGases.Remove(gas.ID);

                    GasSelected(filter);
                };
                _gasControls.Add(gas.ID, gasButton);
                _gases.AddChild(gasButton);
            }
            // funky - end
        }


        private void GasSelected(GasFilterComponent filter)
        {
            SelectGasPressed?.Invoke();
        }

        internal void SetSelectedGases(GasFilterComponent filter)
        {
            foreach (var gas in Enum.GetValues<Gas>())
            {
                if (!Enum.TryParse<Gas>(gas.ToString(), out var gasEnum)) continue;
                _gasControls[gas.ToString()].Pressed = filter.FilteredGases.Contains(gasEnum);
            }

        }
    }
}
