using System.Globalization;
using Content.Shared.Atmos.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;

namespace Content.Client.Atmos.UI
{
    /// <summary>
    /// Client-side UI used to control a gas filter.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class GasFilterWindow : DefaultWindow
    {
        private readonly ButtonGroup _buttonGroup = new();

        public List<string> SelectedGases = new(); // Funky - Allow multiple gases to be filtered

        public event Action<bool>? ToggleStatusButtonPressed;
        public event Action<string>? FilterTransferRateChanged;
        public event Action? SelectGasPressed;

        // funky - start
        private Button _selectAll => CSelectAll;
        private Button _deselectAll => CDeselectAll;

        private GridContainer _gases => CGasContainer;

        private Dictionary<string, Button> _gasControls = new();

        [Dependency] private IEntityManager _entMan = default!;
        [Dependency] private IPrototypeManager _prototypeManager = default!;
        // funky - end

        public GasFilterWindow()
        {
            RobustXamlLoader.Load(this);

            ToggleStatusButton.OnToggled += _ => ToggleStatusButtonPressed?.Invoke(ToggleStatusButton.Pressed);

            FilterTransferRateInput.OnTextChanged += _ => SetFilterRate.Disabled = false;
            SetFilterRate.OnPressed += _ =>
            {
                FilterTransferRateChanged?.Invoke(FilterTransferRateInput.Text);
                SetFilterRate.Disabled = true;
            };

        }

        public void SetTransferRate(float rate)
        {
            FilterTransferRateInput.Text = rate.ToString(CultureInfo.CurrentCulture);
        }

        public void SetFilterStatus(bool enabled)
        {
            ToggleStatusButton.Pressed = enabled;
        }


        public void PopulateGasList(IEnumerable<GasPrototype> gases)
        {
            // funky - start
            _selectAll.OnPressed += _ =>
            {
                SelectedGases = gases.Select(gas => gas.ID).ToList();
                GasSelected();
            };
            _deselectAll.OnPressed += _ =>
            {
                SelectedGases.Clear();
                GasSelected();
            };


            foreach (var gas in gases)
            {
                var gasName = gas.Name;

                var gasButton = new Button
                {
                    Name = gas.ID,
                    Text = Loc.GetString(gasName),
                    ToggleMode = true,
                    HorizontalExpand = true,
                    Pressed = SelectedGases.Contains(gas.ID)
                };

                gasButton.OnToggled += args =>
                {
                    if (args.Pressed)
                        SelectedGases.Add(gas.ID);
                    else
                        SelectedGases.Remove(gas.ID);

                    GasSelected();
                };
                _gasControls.Add(gas.ID, gasButton);
                _gases.AddChild(gasButton);
            }
            // funky - end

        }


        private void GasSelected()
        {
            SelectGasPressed?.Invoke();
        }
    }
}
