using Content.Client.UserInterface.Controls;
using Content.Shared.Radio.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.Radio.Ui;

/// <summary>
/// Pertains to the user interface for the volume / mic sensitivty of a handheld radio
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RadioVolumeMenu : FancyWindow
{
    [Dependency] private IEntityManager _entitys = null!;

    public event Action<int>? OnSliderChanged;

    public RadioVolumeMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        VolumeSlider.OnValueChanged += args => OnSliderChanged?.Invoke((int) args.Value);
    }

    public void Update(Entity<RadioMicrophoneComponent> micEntity)
    {
        VolumeSlider.SetValueWithoutEvent(micEntity.Comp.ListenRange);
    }
    public void Update(Entity<RadioSpeakerComponent> speakerEntity)
    {
        if (!_entitys.HasComponent<RadioMicrophoneComponent>(speakerEntity.Owner))
        {
            VolumeSlider.SetValueWithoutEvent(speakerEntity.Comp.Volume); // dont want two different components setting it at the same time so lets do it here
        }
    }

    public void SetSliderMaxMin(float max, float? min = null)
    {
        VolumeSlider.MinValue = min ?? 1;
        VolumeSlider.MaxValue = max;
    }

    public void UpdateLabels(Entity<RadioMicrophoneComponent> micEntity)
    {
        SensitivityLabel.Visible = true;
        // if the radio has a microphone but not a speaker, let's hide the volume label
        if (!_entitys.HasComponent<RadioSpeakerComponent>(micEntity.Owner))
        {
            VolumeLabel.Visible = false;
            SetHeight = 100;
        }

        // if the max isnt specified or invalid, don't create the number labels
        if (micEntity.Comp.MaxRange == null || micEntity.Comp.MaxRange.Value <= (micEntity.Comp.MinRange ?? 0))
        {
            SensitivityNumbers.Visible = false;
            return;
        }

        var min = micEntity.Comp.MinRange ?? 1;
        var max = micEntity.Comp.MaxRange.Value;
        SensitivityNumbers.Visible = true;
        for (var i = min; i <= max; i++)
        {
            var marginLeft = i == max ? 0 : 1; // try to align number labels with slider just a little better
            var marginRight = i == max ? -1 : 0; // try to align number labels with slider just a little better
            var label = new Label
            {
                Text = i.ToString(),
                Margin = new Thickness(marginLeft ,0, marginRight, 0),
            };
            SensitivityNumbers.AddChild(label);
            // distribute horizontally, with last element flush to the end of the width
            if (i != max)
                SensitivityNumbers.AddChild(new Control{HorizontalExpand = true});
        }
    }

    public void UpdateLabels(Entity<RadioSpeakerComponent> speakerEntity)
    {
        VolumeLabel.Visible = true;
        // if the radio has a speaker but not a microphone, let's hide the sensitivity label
        if (!_entitys.HasComponent<RadioMicrophoneComponent>(speakerEntity.Owner))
        {
            SensitivityLabel.Visible = false;
            SensitivityNumbers.Visible = false;
            SetHeight = 100;
        }
    }
}
