using Content.Client.UserInterface.Controls;
using Content.Shared.Radio.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.Radio.Ui;

[GenerateTypedNameReferences]
public sealed partial class RadioVolumeMenu : FancyWindow
{
    [Dependency] private IEntityManager _entitys = null!;

    public event Action<int>? OnSliderChanged;

    public RadioVolumeMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        VolumeSlider.OnValueChanged += args => OnSliderChanged?.Invoke((int) args.Value);
    }

    public void Update(Entity<RadioMicrophoneComponent> micEntity)
    {
        VolumeSlider.SetValueWithoutEvent(micEntity.Comp.Sensitivity);
        SensitivityLabel.Visible = true;

        if (!_entitys.HasComponent<RadioSpeakerComponent>(micEntity.Owner))
            VolumeLabel.Visible = false;
    }
    public void Update(Entity<RadioSpeakerComponent> speakerEntity)
    {
        VolumeLabel.Visible = true;

        if (!_entitys.HasComponent<RadioMicrophoneComponent>(speakerEntity.Owner))
        {
            SensitivityLabel.Visible = false;
            VolumeSlider.SetValueWithoutEvent(speakerEntity.Comp.Volume); // dont want two different components setting it at the same time
        }
    }
}
