using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Funkystation.StationRecords;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using System.Linq;
using System.Threading;
using Robust.Shared.Utility;
using static System.Int32;
using Timer = Robust.Shared.Timing.Timer;

namespace Content.Client._Funkystation.StationRecords;

[GenerateTypedNameReferences]
public sealed partial class XoRecordsConsoleWindow : FancyWindow
{
    public Action<uint?>? OnKeySelected;
    public Action<uint, XoRecordFields>? OnSubmitted;
    public Action? OnVerifyPressed;
    public Action? OnAddPressed;
    public Action<uint>? OnDeletePressed;

    private bool _isPopulating;
    private uint? _selectedKey;

    private bool _deleteArmed;
    private CancellationTokenSource? _deleteArmCts;
    private static readonly TimeSpan DeleteArmTimeout = TimeSpan.FromSeconds(4);

    private bool _expectingVerifyResponse;

    private readonly List<string> _speciesIds = [];

    public XoRecordsConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        var prototypeManager = IoCManager.Resolve<IPrototypeManager>();

        var successMsg = new FormattedMessage();
        successMsg.AddMarkupOrThrow($"[color=#ccffcc]{Loc.GetString("xo-records-console-verify-none")}[/color]");
        VerifySuccessLabel.SetMessage(successMsg);

        var flaggedMsg = new FormattedMessage();
        flaggedMsg.AddMarkupOrThrow($"[color=#ffcccc]{Loc.GetString("xo-records-console-flagged")}[/color]");
        FlaggedLabel.SetMessage(flaggedMsg);

        foreach (var gender in Enum.GetValues<Gender>())
        {
            GenderButton.AddItem(gender.ToString(), (int)gender);
        }
        GenderButton.OnItemSelected += args => GenderButton.SelectId(args.Id);

        var speciesList = prototypeManager.EnumeratePrototypes<SpeciesPrototype>()
            .Where(x => x.RoundStart)
            .OrderBy(x => Loc.GetString(x.Name));

        foreach (var species in speciesList)
        {
            _speciesIds.Add(species.ID);
            SpeciesButton.AddItem(Loc.GetString(species.Name), _speciesIds.Count - 1);
        }
        SpeciesButton.OnItemSelected += args => SpeciesButton.SelectId(args.Id);

        RecordListing.OnItemSelected += args =>
        {
            if (_isPopulating || RecordListing[args.ItemIndex].Metadata is not uint cast)
                return;

            OnKeySelected?.Invoke(cast);
        };

        RecordListing.OnItemDeselected += _ =>
        {
            if (!_isPopulating)
                OnKeySelected?.Invoke(null);
        };

        VerifyButton.OnPressed += _ =>
        {
            _expectingVerifyResponse = true;
            OnVerifyPressed?.Invoke();
        };
        AddRecordButton.OnPressed += _ => OnAddPressed?.Invoke();

        DeleteRecordButton.OnPressed += _ =>
        {
            if (_selectedKey is not { } key)
                return;

            if (!_deleteArmed)
            {
                ArmDelete();
                return;
            }

            ResetDeleteArm();
            OnDeletePressed?.Invoke(key);
        };

        SubmitButton.OnPressed += _ =>
        {
            HideVerifyFeedback();

            if (_selectedKey is not { } key)
                return;

            TryParse(AgeField.Text.Trim(), out var age);
            var parsedGender = (Gender)GenderButton.SelectedId;
            var speciesId = _speciesIds.Count > 0 ? _speciesIds[SpeciesButton.SelectedId] : "Human";

            int? pagerNumber = TryParse(PagerField.Text.Trim(), out var pVal) ? pVal : null;

            var fields = new XoRecordFields(
                NameField.Text,
                age,
                JobField.Text,
                speciesId,
                parsedGender,
                string.IsNullOrWhiteSpace(FingerprintField.Text) ? null : FingerprintField.Text,
                string.IsNullOrWhiteSpace(DnaField.Text) ? null : DnaField.Text,
                pagerNumber);

            OnSubmitted?.Invoke(key, fields);
        };
    }

    public void UpdateState(XoRecordsConsoleState state)
    {
        if (state.SelectedKey != _selectedKey)
        {
            ResetDeleteArm();
            HideVerifyFeedback();
        }

        _selectedKey = state.SelectedKey;

        PopulateRecordListing(state.Listing, state.SelectedKey);

        if (_expectingVerifyResponse)
        {
            _expectingVerifyResponse = false;
            ShowVerifyFeedback(state.DiscrepancyCount);
        }

        var editable = state.IsEditable;
        AddRecordButton.Disabled = !editable;
        DeleteRecordButton.Disabled = !editable;
        SubmitButton.Disabled = !editable;
        VerifyButton.Disabled = !editable;

        NameField.Editable = editable;
        AgeField.Editable = editable;
        JobField.Editable = editable;
        PagerField.Editable = editable;
        SpeciesButton.Disabled = !editable;
        GenderButton.Disabled = !editable;
        FingerprintField.Editable = editable;
        DnaField.Editable = editable;

        if (state.SelectedKey == null)
        {
            NoSelectionLabel.Visible = true;
            EditForm.Visible = false;
            return;
        }

        NoSelectionLabel.Visible = false;
        EditForm.Visible = true;
        FlaggedBanner.Visible = state.SelectedFlagged;

        NameField.Text = state.Published?.Name ?? string.Empty;
        AgeField.Text = state.Published?.Age.ToString() ?? string.Empty;
        JobField.Text = state.Published?.JobTitle ?? string.Empty;
        PagerField.Text = state.Published?.PagerNumber?.ToString() ?? string.Empty;
        FingerprintField.Text = state.Published?.Fingerprint ?? string.Empty;
        DnaField.Text = state.Published?.Dna ?? string.Empty;

        var genderToSelect = state.Published?.Gender ?? Gender.Epicene;
        GenderButton.SelectId((int)genderToSelect);

        var speciesToSelect = state.Published?.Species ?? "Human";
        var speciesIndex = _speciesIds.IndexOf(speciesToSelect);
        if (speciesIndex >= 0)
            SpeciesButton.SelectId(speciesIndex);
        else if (_speciesIds.Count > 0)
            SpeciesButton.SelectId(0);
    }

    private void ArmDelete()
    {
        _deleteArmed = true;
        DeleteRecordButton.Text = Loc.GetString("xo-records-console-delete-confirm");
        DeleteRecordButton.AddStyleClass(StyleClass.Negative);

        _deleteArmCts?.Cancel();
        _deleteArmCts = new CancellationTokenSource();
        Timer.Spawn(DeleteArmTimeout, ResetDeleteArm, _deleteArmCts.Token);
    }

    private void ResetDeleteArm()
    {
        _deleteArmed = false;
        _deleteArmCts?.Cancel();
        _deleteArmCts = null;
        DeleteRecordButton.Text = Loc.GetString("xo-records-console-delete-record");
        DeleteRecordButton.RemoveStyleClass(StyleClass.Negative);
    }

    private void HideVerifyFeedback()
    {
        VerifySuccessBanner.Visible = false;
        VerifyWarningBanner.Visible = false;
    }

    private void ShowVerifyFeedback(int discrepancyCount)
    {
        HideVerifyFeedback();

        if (discrepancyCount == 0)
        {
            VerifySuccessBanner.Visible = true;
        }
        else
        {
            VerifyWarningBanner.Visible = true;

            var warningMsg = new FormattedMessage();
            warningMsg.AddMarkupOrThrow($"[color=#ffcc88]{Loc.GetString("xo-records-console-verify-flagged", ("count", discrepancyCount))}[/color]");
            VerifyWarningLabel.SetMessage(warningMsg);
        }
    }

    private void PopulateRecordListing(List<XoRecordListingEntry> listing, uint? selected)
    {
        RecordListing.Clear();
        RecordListing.ClearSelected();

        RosterEmptyLabel.Visible = listing.Count == 0;
        RecordListing.Visible = listing.Count > 0;

        _isPopulating = true;

        var sortedListing = listing.OrderBy(x => x.DisplayName).ToList();

        foreach (var entry in sortedListing)
        {
            var text = entry.Flagged
                ? Loc.GetString("xo-records-console-roster-flagged-entry", ("name", entry.DisplayName))
                : entry.DisplayName;

            var item = RecordListing.AddItem(text);
            item.Metadata = entry.Id;
            item.Selected = entry.Id == selected;
        }

        _isPopulating = false;
    }
}
