- type: loadoutGroup
  id: FuHdHead
  name: fu-loadout-group-hd-head
  minLimit: 0
  loadouts:
  - FuHdPillboxHat
  - FuHdTopHat

- type: loadoutGroup
  id: FuHdOuterclothing
  name: fu-loadout-group-hd-outerclothing
  minLimit: 0
  loadouts:
  - FuHdCoat
  - FuHdVest
  - FuHdWinterCoat

- type: loadoutGroup
  id: FuHdUniform
  name: fu-loadout-group-hd-uniform
  loadouts:
  - FuHdShirtPants
  - FuHdShirtSkirt

- type: loadoutGroup
  id: FuHdGloves
  name: fu-loadout-group-hd-gloves
  minLimit: 0
  loadouts:
  - WhiteGloves # They don't get any other color options because that would be a COMPLETE stylistic faux pas. Gotta Mickey Mousemaxx.

- type: loadoutGroup
  id: FuHdShoes
  name: fu-loadout-group-hd-shoes
  loadouts:
  - FuHdLaceupBoots # putting this first so it's the default
  - FuHdHighHeelBoots

# Janitor
- type: loadoutGroup
  id: FuJaniHead
  name: fu-loadout-group-jani-head
  minLimit: 0
  loadouts:
  - FuRainHat

- type: loadoutGroup
  id: FuJaniOuterclothing
  name: fu-loadout-group-jani-outerclothing
  minLimit: 0
  loadouts:
  - FuRainCoat

- type: loadoutGroup
  id: FuJaniUniform
  name: fu-loadout-group-jani-uniform
  loadouts:
  - FuJaniJumpsuitPurple
  - FuJaniJumpsuitGreen
  - FuJaniJumpsuitOrange
  - FuJaniJumpskirtPurple
  - FuJaniJumpskirtGreen
  - FuJaniJumpskirtOrange
  - FuJaniOverallsPurple
  - FuJaniOverallsGreen
  - FuJaniOverallsOrange
  - FuJaniOverallSkirtPurple
  - FuJaniOverallSkirtGreen
  - FuJaniOverallSkirtOrange

- type: loadoutGroup
  id: FuJaniGloves
  name: fu-loadout-group-jani-gloves
  minLimit: 0
  loadouts:
  - FuJaniGlovesYellow
  - FuJaniGlovesPurple
  - FuJaniGlovesTeal
  - FuJaniGlovesOrange

- type: loadoutGroup
  id: FuJaniGaloshes
  name: fu-loadout-group-jani-shoes
  loadouts:
  - FuJaniGaloshesYellow
  - FuJaniGaloshesPurple
  - FuJaniGaloshesTeal
  - FuJaniGaloshesOrange
