- type: loadoutGroup
  id: FuHdHead
  name: fu-loadout-group-hd-head
  minLimit: 0
  loadouts:
  - FuHdPillboxHat
  - FuHdTopHat

- type: loadoutGroup
  id: FuHdOuterclothing
  name: fu-loadout-group-hd-outerclothing
  minLimit: 0
  loadouts:
  - FuHdCoat
  - FuHdVest
  - FuHdWinterCoat

- type: loadoutGroup
  id: FuHdUniform
  name: fu-loadout-group-hd-uniform
  loadouts:
  - FuHdShirtPants
  - FuHdShirtSkirt

- type: loadoutGroup
  id: FuHdGloves
  name: fu-loadout-group-hd-gloves
  minLimit: 0
  loadouts:
  - WhiteGloves # They don't get any other color options because that would be a COMPLETE stylistic faux pas. Gotta Mickey Mousemaxx.

- type: loadoutGroup
  id: FuHdShoes
  name: fu-loadout-group-hd-shoes
  loadouts:
  - FuHdLaceupBoots # putting this first so it's the default
  - FuHdHighHeelBoots
