# Partial prototypes start

# TODO: Move other modifications we made to the protos here

- type: startingGear
  id: DetectiveGear
  equipment:
    eyes: ClothingEyesGlassesSunglasses

# Partial prototypes end
