- type: job
  id: Lieutenant
  name: job-name-lieutenant
  description: job-description-lieutenant
  playTimeTracker: JobLieutenant
  requirements:
  - !type:RoleTimeRequirement
    role: JobSecurityOfficer
    time: 5h
  startingGear: LieutenantGear
  icon: "JobIconDeputy"
  supervisors: job-supervisors-commandant
  access:
  - Security
  - Brig
  - Maintenance
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: LieutenantGear
  equipment:
    id: LieutenantPDA
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity
    pocket2: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol

- type: chameleonOutfit
  id: LieutenantChameleonOutfit
  job: Lieutenant
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretSecurity
    mask: ClothingMaskGasSecurity
    neck: Dinkystar
    gloves: ClothingHandsGlovesColorBlack
